### ISSUE TITLE
Make it possible to disable creation of the 'keycloak-http' service

### ISSUE THREAD

**Issue by ovk** [codecentric/helm-charts#10]
It would be nice if the `keycloak-http` service would be optional, so that user can request not to create it at all during chart installation.

The reason is, for example, when using Ambassador as an API gateway, the only entry point to the Keycloak would be though the headless service. Having also `keycloak-http` service means it may have to be secured as well (when using Ambassador in combination with Istio and mutual TLS), and in general complicates and pollutes configuration.

**Comment by unguiculus** [comment]
I'll think about it. However, security-wise, this shouldn't be an issue. Feel free to come up with a PR.
