### ISSUE TITLE
How to configure ingress to use aws alb??

### ISSUE THREAD

**Issue by cocowowo** [codecentric/helm-charts#105]
I want to configure ingress controller for keycloak.
I set values.yaml like this.
``` 
 ## Ingress configuration.
  ## ref: https://kubernetes.io/docs/user-guide/ingress/
  ingress:
    enabled: true
    path: /

    annotations: {
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:....,
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]',
      alb.ingress.kubernetes.io/scheme: internet-facing,
      kubernetes.io/ingress.class: alb
    }

    labels: {}
    # key: value

    ## List of hosts for the ingress
    hosts:
      - mykeycloak.test.com

    ## TLS configuration
    tls: []
    # - hosts:
    #     - keycloak.example.com
    #   secretName: tls-keycloak
```

but it didn't work.
Please help me.

**Comment by unguiculus** [comment]
I'm not familiar with the ALB ingress controller. I could try and help but you'd have to provide more information.

**Comment by cocowowo** [comment]
@unguiculus Thank you. I installed keycloak on AWS EKS.  And I have domain registered in AWS Route53 and I will use AWS Certification Manager to generate ssl certificate. 
I want to connect to keycloak using my domain.
I think " ## Ingress configuration." will create ingress controller with tls configuration.
But I can't find example to reference that configure with aws alb.
Do need more information?

**Comment by unguiculus** [comment]
The ingress configuration will not install the ingress controller. It will create an ingress object that the ingress controller picks up. You have to install an ingress controller separately.
