### ISSUE TITLE
Support additionnal podAnnotations with templated string format

### ISSUE THREAD

**Issue by RaphC** [codecentric/helm-charts#113]
Hi, I need to extends podAnnotations in order to set a new ConfigMap checksum reference.

The template only accept plain value

    template:
    metadata:
      labels:
        {{- include "keycloak.selectorLabels" . | nindent 8 }}
        {{- with .Values.keycloak.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config-sh: {{ include (print .Template.BasePath "/configmap-sh.yaml") . | sha256sum }}
        checksum/config-startup: {{ include (print .Template.BasePath "/configmap-startup.yaml") . | sha256sum }}
        {{- with .Values.keycloak.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

Is it possible to use templated format like extraContainers ?

Regards

**Comment by unguiculus** [comment]
Can you elaborate and maybe sketch out an example? I don't fully understand why this is necessary. What needs to be templated?

**Comment by RaphC** [comment]
Hi @unguiculus 

I want to add an extra Container with my own extension configuration file and I want to reload pod when this file are changes. As far as I read, the best approach for this is to add podAnnotations  containing checksum  of my file and then when OpenShift detects a change of value it triggers pod rolling update.

Regards

**Comment by unguiculus** [comment]
Implemented in #122. Would you mind testing it?

**Comment by RaphC** [comment]
Sure I will test it.
Thanks
