### ISSUE TITLE
Keycloak: Pass existingSecret through tpl

### ISSUE THREAD

**Issue by Panaetius** [codecentric/helm-charts#115]
According to helm best practices, resource names should be prefixed with the release name. So if one follows that and names a secret accordingly, it can't be used for the `keycloak.existingSecret` value since templating is not supported in Helm values.yaml.
 This can be worker around with using the `tpl` function, e.g. `extraEnv` is already passed through `tpl` to allow setting templated values in a parent chart's `values.yaml`.

Would it be possible to run `keycloak.existingSecret` through `tpl` as well, so a parent chart could do something like:

```
keycloak:
  keycloak:
    existingSecret: '{{.Release.Name}}-keycloak-secret'
```
I'd happily make a PR for this if this suggestion isn't rejected :smile:

**Comment by unguiculus** [comment]
Implemented in #122. Would you mind testing it?

**Comment by Panaetius** [comment]
Wow, thanks a lot for the quick fix! I'll try and test it today and get back to you with feedback.

**Comment by Panaetius** [comment]
I tested it and everything works fine on my end with the `6.0.0` chart.

Thank you again :tada:
