### ISSUE TITLE
validation failed

### ISSUE THREAD

**Issue by CoosDUO** [codecentric/helm-charts#125]
When I run this command (on chart keycloak-5.1.7): 
`helm install --name keycloak --set keycloak.replicas=2,keycloak.persistence.deployPostgres=true,keycloak.persistence.dbVendor=postgres codecentric/keycloak`

I get this response:
> Error: validation failed: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"

If I leave out the deployPostgres=true,dbVendor=postgres it works fine.

I'm running:
Windows 10
Minikube v1.4.0
Helm v2.14.3

**Comment by CoosDUO** [comment]
The error is the same for any 5.x.x version. If I change the version to any 4.x.x it changes into:

> Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

**Comment by Jabbo16** [comment]
Try this
https://github.com/codecentric/helm-charts/pull/117

**Comment by unguiculus** [comment]
This is because `extensions/v1beta1` is no longer supported from 1.16. A new release is available that updates the Postgresql version.
