### ISSUE TITLE
Ingress returns 404 in GKE

### ISSUE THREAD

**Issue by aodj** [codecentric/helm-charts#127]
When deploying the chart to GKE an `Ingress` resource is created, which doesn't have a [default backend](https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#default_backend) configured. This results in the following message "`default backend - 404`" when accessing the created load balancer.

This occurs because the created `Ingress` defines a route, `/`, under the rules section which doesn't match the default forwarding address for keycloak, `/auth` (as defined by `.basepath`). The documentation for GKE HTTP Load Balancer describes this behaviour:
> If you don't specify a default backend, GKE provides a default backend that returns 404.

It's possible to patch the `Ingress` to define a default backend:
```bash
kubectl patch ingress keycloak -p '{"spec":{"backend":{"serviceName":"keycloak-http","servicePort":"http"}}}'
```
but this is less than ideal.

Alternatively, by setting the value of `.ingress.path` to `/*` the rule in the `Ingress` can match any child URI, for example `/auth`. This is the better solution since it's fully encapsulated by the chart.

This isn't documented anywhere to help new users; I only found one issue that was related to this (#74) and the answer directed users to check the configuration of their `IngressController`, something I'm not sure is possible with the default GKE setup (ie: which makes use of GCP Cloud Load Balancers).

**Comment by unguiculus** [comment]
The ingress path is configurable. It defaults to `/` but you can change it to achieve what you need.

```yaml
keycloak:
  ingress:
    path: "/*"
```
