### ISSUE TITLE
Issue with Tille v2.15.0

### ISSUE THREAD

**Issue by mvalenzisiAK** [codecentric/helm-charts#130]
Hello,

I discovered an issue using the Keycloak chart on a Kubernetes cluster with Tiller v2.15.0:

it looks like that this instruction
`{{- $highAvailability := gt (int .Values.keycloak.replicas) 1 -}}`
is not evaluated correctly when `keycloak.replicas` is set as an integer (always false). If it is set as a string it works.

On a different cluster where I use Tiller v2.14.3, it works with `keycloak.replicas` as an integer.

So, I presume that the Tiller version makes the difference, but I might be wrong.
I just wanted to point that out to you guys.

**Comment by dojadop** [comment]
I am also seeing this issue where highAvailability configuration isn't working on Helm 2.15. Here is the related helm issue: https://github.com/helm/helm/issues/6708

**Comment by dojadop** [comment]
I updated to 2.15.1 and everything is working as before so this was a bug with helm. I think this issues can be closed.

**Comment by mvalenzisiAK** [comment]
@dojadop thanks for checking this out!
