### ISSUE TITLE
gremlin in current version

### ISSUE THREAD

**Issue by dmpe** [codecentric/helm-charts#134]
Hi, 
just download master version of your chart, and after many trials and errors I think I found a gremlin. 

(https://marketplace.visualstudio.com/items?itemName=nhoizey.gremlins)

file https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/templates/statefulset.yaml#L65 and L66

**Comment by gzur** [comment]
What failure were you experiencing? Did removing that line solve the issue?

**Comment by dmpe** [comment]
Sorry it was my mistake. I was too qucik with the analysis. You code seems to be fine.
