### ISSUE TITLE
PROXY_ADDRESS_FORWARDING is no longer a default external variable

### ISSUE THREAD

**Issue by mikhail-putilov** [codecentric/helm-charts#138]
I didn't quite catch the time when this parameter was taken out from default ones, but it is still written in README as a default one. Today I tried to run `helm upgrade ` and got stuck since this environment variable was not there.

Without this, I had "Invalid parameter: redirect_uri" in the admin console.

**Comment by mikhail-putilov** [comment]
I added this:
```
  extraEnv: |
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
```
and all get back to normal again.

**Comment by unguiculus** [comment]
Documentation was updated in #161.
