### ISSUE TITLE
helm upgrade fails with helm3

### ISSUE THREAD

**Issue by m-ayyz** [codecentric/helm-charts#141]

**Comment by m-ayyz** [comment]
I get the following error while performing helm upgrade 

Error: UPGRADE FAILED: cannot patch "develop-mailhog" with kind Service: Service "develop-mailhog" is invalid: spec.clusterIP: Invalid value: "": field is immutable

On googling found the following info
https://github.com/helm/helm/issues/6378

**Comment by unguiculus** [comment]
Can you share your configuration? The clusterIP is only set if explicitly specified but not when it is empty. I could not reproduce this with a normal upgrade.

**Comment by max-lobur** [comment]
Same here, couldn't pass any vars (passing via -f). Installation from scratch. Ingress is not creating (cause default is false and couldn't override). Also couldn't override db from h2 to postgres. Basically vars do not take effect. 
Not sure if it's chart or helm3 issue now (using `version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}`)

**Comment by unguiculus** [comment]
This a Helm 3 issue. Here's a PR that attempts to solve the problem: https://github.com/helm/helm/pull/7431
