### ISSUE TITLE
Make it possible to configure tls certificate and key using values fail for keycloak route

### ISSUE THREAD

**Issue by m-ayyz** [codecentric/helm-charts#147]
It would be nice if it could be possible to configure tls certificate and key using values file. Refer to the existing code snippet below

https://github.com/codecentric/helm-charts/blob/181e328faa9ffe17c753b8e5b5dfa5c54755f0b6/charts/keycloak/templates/route.yaml#L27

By changing this to 
`{{- with .$route.tls }}
      tls:
{{ toYaml . | indent 4 }}`
it can be more generic

**Comment by unguiculus** [comment]
You're welcome to submit a PR for this.

**Comment by unguiculus** [comment]
Closing as stale.
