### ISSUE TITLE
Support AWS managed postgres (all db connection params from secret)

### ISSUE THREAD

**Issue by strowk** [codecentric/helm-charts#148]
AWS can give access to RDS postgres with service catalog, but it passes database name, user name, port and address (host) via secret, which is not supported by this chart, chart only receives password to database via secret. We need to use AWS managed postgres with keycloak, so it would be nice if it was supported in some way.
We managed to workaround override env by using extraEnv, though it looks a bit dirty.

**Comment by unguiculus** [comment]
The latest rewrite of the chart doesn't make any assumptions on how you configure the database. You should be able to achive what you need.
