### ISSUE TITLE
Keycloak failed to port forward in combination with Consul

### ISSUE THREAD

**Issue by fskroes** [codecentric/helm-charts#150]
Hi,

I have a Minikube cluster on my macOS Catalina.
```
minikube version: v1.5.2
commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad
```
I have installed Consul via Helm and it also wants access to port 80 therefore, I have changed the property value of `keycloak.service.httpPort` in values.yaml to an arbitrary number. This resolved the issue that the base page is being loaded, but when I try to log into the keycloak admin console it will give an error forwarding port 8080 to pod x. (see attached screenshot from error)

![image](https://user-images.githubusercontent.com/10432545/69962842-23f25c00-150f-11ea-95cd-66444ca48732.png)

Does anybody have a slight idea on how to tackle this problem? Any help is much appreciated.

Thank you in advance 💯

**Comment by unguiculus** [comment]
Each pod get its own IP so different pods can have the same port. They don't interfere. Port-forwarding goes to the pod, not via service, so changing the service port doesn't make sense.

I'm going to close this issue. It's more of a generic Kubernetes question and not related to this chart. Thanks.
