### ISSUE TITLE
Keycloak prometheus metrics setup

### ISSUE THREAD

**Issue by y0zg** [codecentric/helm-charts#152]
Please consider checking option to add prometheus metrics exporter

Examples:
https://github.com/aerogear/keycloak-metrics-spi
https://github.com/larscheid-schmitzhermes/keycloak-monitoring-prometheus

**Comment by Rjvs** [comment]
You might also be interested in #58 (which is awaiting review).

**Comment by unguiculus** [comment]
Closing this since #58 was merged.
