### ISSUE TITLE
Keycloak - kube-score

### ISSUE THREAD

**Issue by ByJacob** [codecentric/helm-charts#153]
Hi
I use [kube-score](https://github.com/zegl/kube-score) in my app, and have keycloak in requirements. Unfortunately keycloak don't have enought option to configure to pass this tests:
- don't have possible to add annotation in tests - `kube-score/ignore`
- don't have possible to add networkPolicy

**Comment by unguiculus** [comment]
Thanks for your request. You're welcome to come up with a PR.

**Comment by unguiculus** [comment]
Closing as stale.
