### ISSUE TITLE
can't evaluate field existingSecret in type interface {}

### ISSUE THREAD

**Issue by zeph** [codecentric/helm-charts#162]
as reported in https://github.com/helm/helm/issues/1579#issuecomment-574678032

it's going haywire when using the same structure in a lower scope of the helm tree

I'd recommend applying the same patch to the
 `template: codecentric/charts/keycloak/templates/_helpers.tpl:127:47`

**Comment by unguiculus** [comment]
Obsolete with the latest version of the chart.
