### ISSUE TITLE
/proc/1/task/1/pagemaps Filling up all the Node disk space

### ISSUE THREAD

**Issue by ginesete** [codecentric/helm-charts#165]
Installing Keycloak with the Helm chart with 2 replicas for HA, I encountered that the node that hosts keycloak-0 gets to a DiskPressure failure.

Inside the Node, I could see that the pagemap file occupied 13G.

My values.yml file is appended.
[values.yml.txt](https://github.com/codecentric/helm-charts/files/4086315/values.yml.txt)

**Comment by unguiculus** [comment]
It's unlikely that this is related to the chart itself. You may want to open an issue with Keycloak or ask on the mailing list.
