### ISSUE TITLE
Upgrading Keycloak to 9.0.0

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [codecentric/helm-charts#177]
It seems Keycloak 9.0.0 has quite a few [new features](https://www.keycloak.org/2020/02/keycloak-900-released.html) which improves the QoL for devs. But the Helm chart provides only upto 8.0.1, not even 8.0.2. It would be great if charts for 9.0.0 could be made.

**Comment by briantopping** [comment]
Here's another good reason to get to 9.x:
<img width="772" alt="Screen Shot 2020-02-29 at 11 54 47 PM" src="https://user-images.githubusercontent.com/158115/75621268-381a1980-5b4f-11ea-97f1-92b24308fbb2.png">

**Comment by Bessonov** [comment]
https://github.com/codecentric/helm-charts/pull/189

**Comment by unguiculus** [comment]
Current version is now at Keycloak 10.
