### ISSUE TITLE
[keycloak] Improvement: Support external Infinispan cluster

### ISSUE THREAD

**Issue by shousper** [codecentric/helm-charts#183]
Any interest in supporting an option to either: use an external/existing Infinispan cluster or deploy Infinispan as a separate stateful set?

**Comment by unguiculus** [comment]
I'm afraid I don't have enough WildFly knowledge for this. Also, I think this would make to chart even more complex and harder to support. You'd have to roll your own for such scenarios.

**Comment by unguiculus** [comment]
Closing this. With the major rewrite, the chart tries to no longer be opinionated. It should be possible to configure everything you need. I'd be happy to add a section to the readme on how to configure that. I'd appreciate a PR or just share your configs here.
