### ISSUE TITLE
[keycloak] DB_PASSWORD secret name is hardcoded 

### ISSUE THREAD

**Issue by oscarlofwenhamn** [codecentric/helm-charts#184]
https://github.com/codecentric/helm-charts/blob/c6207dfa52f7285ce10f432adcbdd8a49f421839/charts/keycloak/templates/_helpers.tpl#L166

This means setting `existingSecret` is ignored, causing an error if the authentication secret isn't named equivalent of `{{ include "keycloak.postgresql.fullname" . }}`.

**Comment by unguiculus** [comment]
You can specify an existing secret if you configure your own database. This is not supported if you use Postgres as a dependency which is anyways not advisable for production scenarios.

**Comment by oscarlofwenhamn** [comment]
Fair enough, though the behavior is still unexpected. It would be nice to see this detailed in documentation, as I am guessing this will be a wontfix functionality-wise,

**Comment by unguiculus** [comment]
Aynways, this would be part of the Postgres dependency, which, I think, has an option to configure an existing secret. So, we may be able to do that. I'll try and have a look.

**Comment by unguiculus** [comment]
I assume this can be closed now.
