### ISSUE TITLE
Service set to ClusterIP not possible

### ISSUE THREAD

**Issue by gwsch** [codecentric/helm-charts#193]
Changing the config below from NodePort -> ClusterIP fails to deploy:

Unable to upgrade the release: cannot patch "keycloak-http" with kind Service: Service "keycloak-http" is invalid: [spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP', spec.ports[1].nodePort: Forbidden: may not be used when `type` is 'ClusterIP']:

A first guess is using an ingress.

## Optionally override the fully qualified name
# fullnameOverride: keycloak
## Optionally override the name
# nameOverride: keycloak
keycloak:

  ## Override the default for the Keycloak container, e.g. for clusters with large cache that requires rebalancing.
  terminationGracePeriodSeconds: 60

  ## Username for the initial Keycloak admin user
  username: pbadmin

  ## Password for the initial Keycloak admin user. Applicable only if existingSecret is not set.
  ## If not set, a random 10 characters password will be used
  password: 4325sre765
  # maxUnavailable: 1
  # minAvailable: 1
  service:
    # key: value
    ## ServiceType
    ## ref: https://kubernetes.io/docs/user-guide/services/#publishing-services---service-types
    type: NodePort

  ## Ingress configuration.
  ## ref: https://kubernetes.io/docs/user-guide/ingress/
  ingress:
    enabled: true
    path: /
    # key: value
    ## List of hosts for the ingress
    hosts:
      - auth.local
      - auth.<my domain>
    # - hosts:
    #     - keycloak.example.com
    #   secretName: tls-keycloak
  ## Persistence configuration
  persistence:
    # If true, the Postgres chart is deployed
    deployPostgres: false

    # The database vendor. Can be either "postgres", "mysql", "mariadb", or "h2"
    dbVendor: postgres

    ## The following values only apply if "deployPostgres" is set to "false"
    dbName: keycloak
    dbHost: powerful-pigs-postgresql.pb.svc.cluster.local
    dbPort: 5432

    ## Provision new Secret
    # Only used if existingSecret is not specified. In this case a new secret is created
    # populated by the variables below.
    dbUser: keycloak
    dbPassword: keycloak

**Comment by timothyclarke** [comment]
```
Unable to upgrade the release: cannot patch "keycloak-http" with kind Service: Service "keycloak-http" is invalid: [spec.ports[0].nodePort: Forbidden: may not be used when type is 'ClusterIP', spec.ports[1].nodePort: Forbidden: may not be used when type is 'ClusterIP']:
```
That error is a kubernetes error, rather than specific to this chart. You will need to remove and re-add the chart to make that sort of change

**Comment by unguiculus** [comment]
Closing as answered. Thanks @timothyclarke.
