### ISSUE TITLE
Improperly specified VM option 'MinRAMPercentage=50'

### ISSUE THREAD

**Issue by stevenklar** [codecentric/helm-charts#195]
Hey, your latest update crashed our keycloak because of this:

```javaToolOptions: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=50"```

which actually must be

```javaToolOptions: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=50.0"```

for older environments (jvm versions).

Because keycloak/java expects a double in this case. Otherwise it alway cashes with the error mentioned in headline. A better default therefore wold be 50.0 instead of 50.

Related doc what causes this issue: https://merikan.com/2019/04/jvm-in-a-container/

**Comment by unguiculus** [comment]
Fixed in #196
