### ISSUE TITLE
Theme is not loaded 

### ISSUE THREAD

**Issue by dzbeda** [codecentric/helm-charts#200]
Hi, 
In Kubernetes environment 
I have created init container following the documentation with my own theme folders and files.
The files are been copied to the PODs (replication 2) under keycloak theme directory, but when browsing the keycloak admin UI under the theme category, I can not find the theme.

BTW, 
I took the same theme folder and copy it to a keyclock running under native ubuntu and it is working.

**Comment by dzbeda** [comment]
Problem in my side

**Comment by Jay-Funk** [comment]
@dzbeda it would be great if you could share the solution to your problem with us so that someone else who is running into the same problem, like me, might be able to learn from it.

**Comment by exaucae** [comment]
Indeed @Jay-Funk! I face the same issue with no clue at all.  Bump @dzbeda
