### ISSUE TITLE
Keycloak kuberntes - Adding Customize protocol mapper

### ISSUE THREAD

**Issue by dzbeda** [codecentric/helm-charts#201]
Hi , 
Is there an option y to add customize protocol mapper ?
I have loaded the files using init container (like updating theme files) , but for protocol mapper, i will need to update the provider in the standalone -ha .xml file

**Comment by unguiculus** [comment]
You can add custom cli commands with `keycloak.cli.custom` or configure complete startup scripts with `keycloak.startupScripts`.
