### ISSUE TITLE
keycloak.extraArgs don't seem to work to configure Liquibase

### ISSUE THREAD

**Issue by kjgaul1** [codecentric/helm-charts#202]
Liquibase is putting the databasechangeloglock table in the public schema and I have to put it in the same schema with the rest of the tables.  I have tried using keycloak.extraArgs to pass in "-Dliquibase.liquibaseSchemaName=my_schema-Dliquibase.liquibaseCatalogName=my_schema" but I still see in the logs trying to create the table in public.

Using the version 9.0.2, postgres with existing secret in AWS.

**Comment by unguiculus** [comment]
You can't set system proerties as Keycloak args. Add it to `JAVA_TOOL_OPTIONS` (`keycloak.javaToolOptions`). See https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/values.yaml#L104-L106.
