### ISSUE TITLE
Security/group issues on Openshift

### ISSUE THREAD

**Issue by yntelectual** [codecentric/helm-charts#203]
Hi, I am trying to deploy this chart to our Openshift 4.3 cluster and run into security constraint issues:
For postresql:
```
create Pod keycloak-postgresql-0 in StatefulSet keycloak-postgresql failed error: pods "keycloak-postgresql-0" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{1001}: 1001 is not an allowed group spec.initContainers[0].securityContext.securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1000600000, 1000609999] spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1001: must be in the ranges: [1000600000, 1000609999]]
```
For keycloak, I can modify the `runAsUser` value to a value in the allowed range which fixes this issue, but it then fails on another `fsGroup` related error:
```
create Pod keycloak-0 in StatefulSet keycloak failed error: pods "keycloak-0" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{1000}: 1000 is not an allowed group]
```

Any suggestions? Thanks

**Comment by materia2021** [comment]
happens to me too. any workarounds?

**Comment by MarianZoll** [comment]
@yntelectual @materia2021 

Running with a huge number for the `fsGroup` and `runAsUser` will resolve this on OCP. Just add this to your `values.yaml`

```
keycloak:
  securityContext: 
    fsGroup: 1001750000

  containerSecurityContext:
    runAsUser: 1001750000
    runAsNonRoot: true
```

Might make sense to add this as a config param in the helm chart to ease deployment on OCP, but I am not sure whether this makes sense to everyone.

**Comment by unguiculus** [comment]
The Keycloak Docker image has a user with ID 1000.

See https://github.com/keycloak/keycloak-containers/blob/master/server/Dockerfile#L25

The chart considers this  when setting security context. As mentioned above, you may change that.
