### ISSUE TITLE
404 when adding https://codecentric.github.io/helm-charts

### ISSUE THREAD

**Issue by kelimutu** [codecentric/helm-charts#21]
The following chart repo mentioned in README.md is not found:
https://codecentric.github.io/helm-charts

**Comment by unguiculus** [comment]
Well, there actually is an `index.yaml` at the repo root, which is what counts.

https://codecentric.github.io/helm-charts/index.yaml

We have plans to add an index page, though, for those who open it in the browser 😉.

**Comment by unguiculus** [comment]
Added redirect to GitHub.
