### ISSUE TITLE
[Keycloak] How to add json to realm without unpacking the chart.

### ISSUE THREAD

**Issue by hatharom** [codecentric/helm-charts#210]
I have this chart as a packed tgz dependency in ./charts

I have followed the following description:
https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#setting-a-custom-realm

I overwrote those properties in my main chart's Values.yml, but the last step is missing: 
How in the hell should I put my realm.json there?? Be it a secret or configmap I dont want to create it via kubectl, but with configmap/secret.yaml.

No..I dont want to unpack and modify the chart (this the reason why we use the overwritten Values.yml). How should we provide that json for the configmap?

So how is it supposed to work?

**Comment by igorfernandes** [comment]
You can use the same as theme?

https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#providing-a-custom-theme

I use the same approach to put NewRelic agent inside keycloak container.
