### ISSUE TITLE
HA functionality does NOT automagically enable replication of data between nodes

### ISSUE THREAD

**Issue by frittentheke** [codecentric/helm-charts#214]
Thanks for providing and maintaining this helm-chart for Keycloak. 

When looking at issue (https://github.com/helm/charts/issues/10561) in the former helm-chart repo where someone has issues with the clustering, I noticed you are not automagically enabling replication when running in cluster mode.

Even though you set up HA (https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/templates/statefulset.yaml#L97) the caches (i.e. holding user sessions) are not replicated.

I added easy configuration of the replication count via https://issues.redhat.com/browse/KEYCLOAK-10151 or rather https://github.com/keycloak/keycloak-containers/pull/192.

Maybe it would be good to make this a little easier and not have people believe with HA they can do rolling upgrades without data loss.

**Comment by unguiculus** [comment]
Thanks for bringing this up. I haven't seen any issue so far. The chart does this so far: https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/scripts/ha.cli

With your change, it seems we can improve the chart. Would you mind creating a PR?

**Comment by frittentheke** [comment]
1. @unguiculus ah I missed that you glob in this custom ha.cli script (https://github.com/codecentric/helm-charts/blob/9b69a283a30b50e0673c7d92706cdd9c24f845fc/charts/keycloak/values.yaml#L190). This seems, considering this is a Helm chart with values.yaml as the intended main point to contact / config for the user deploying it, a little bit too much indirection don't you think?  Looking at all those ENV variables the image can take to be configured without injecting any custom WildFly scripts ... https://hub.docker.com/r/jboss/keycloak
You even have the `extraEnv` list to allow everything the image can do out of the box ... https://github.com/codecentric/helm-charts/blob/9b69a283a30b50e0673c7d92706cdd9c24f845fc/charts/keycloak/values.yaml#L109 with the CACHE_OWNERS example in there.

2. Things like the additonal datasource or logging options to me should not remain a custom addition  in this Helm chart, but rather be part of the actual software image itself (https://github.com/codecentric/helm-charts/blob/9b69a283a30b50e0673c7d92706cdd9c24f845fc/charts/keycloak/scripts/datasource.cli). 
This would reduce complexity of the chart a lot and have all those options be validated, curated and unit tested by the image maintainers.



Certainly the Helm chart could help in addressing a few functions like HA with a whole set of env variables set accordingly, but with the Keycloak image so rich in external config switches it should not need to manage all the gory details.

**Comment by unguiculus** [comment]
@frittentheke You've raised some good points. The Keycloak Docker image has come a long ways since I created this chart. Many things are now possible with the Docker image directly and the chart could probably receive a major overhaul. This is on my list of things to look at. I just haven't gotten around to doing it.

That being said, I'm open for suggestions. Feel free to draft something up in an issue or PR.

**Comment by Jaorji** [comment]
@frittentheke @unguiculus Can I please ask if there is a solution for this issue, I'm stuck at replication of data between node?

**Comment by unguiculus** [comment]
Meanwhile, the chart has been completely revised. HA is documented here:
https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#high-availability-and-clustering
