### ISSUE TITLE
keycloak chart on helm 3.2 give the error "Error: unknown flag: --name"

### ISSUE THREAD

**Issue by MirtoBusico** [codecentric/helm-charts#223]
When I try to install keycloak chart on helm 3.2 I receive the error "Error: unknown flag: --name"

```
sysop@hoseplak3s:~/software/keycloak$ helm version
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
sysop@hoseplak3s:~/software/keycloak$ sudo helm install --name keycloak codecentric/keycloak
Error: unknown flag: --name
sysop@hoseplak3s:~/software/keycloak$ 
```
What is the correct syntax?

**Comment by igorfernandes** [comment]
Didi you try: 
`helm install keycloak codecentric/keycloak`

**Comment by MirtoBusico** [comment]
Yes and it works
I installed using the command:
`helm install --namespace=keycloack -f values.yaml keycloak codecentric/keycloak`
I had to download the values.yaml from the github repository because I have Istio installed on kubernetes and it conflicts with port 80
The installation seems good; but trying to curl the token endpoint gives a server internal error
The web interface works corretly and I able to manage keycloak

Can I suppose that the installation is correct and that problems are related to Istio interferences?
