### ISSUE TITLE
High Availability

### ISSUE THREAD

**Issue by KaiWedekind** [codecentric/helm-charts#23]
Hi,

how can I run Keycloak in HA mode? When I change keycloak replicas to higher than one, then I get an error with pod affinity.

Thanks in advance!

**Comment by unguiculus** [comment]
By default, affinity is configured such that all replicas must be scheduled on different nodes. If you don't have this many nodes, pods can be scheduled. You'd have to reconfigure affinity.

**Comment by KaiWedekind** [comment]
@unguiculus Thanks, I reconfigured affinity and it works now.
