### ISSUE TITLE
Keycloak dbHost value contains variables (Known at runtime)

### ISSUE THREAD

**Issue by naoufal450** [codecentric/helm-charts#234]
Hi,

My Postgres service name is dependent on the Release.Name, it looks like this:
`{{ .Release.Name }}-postgresql `

`keycloak.keycloak.persistence.dbHost: {{ .Release.Name }}-postgresql` won't work. is there a way to overcome this issue?
I'm thinking that doing something like this might work (_helpers.tpl):
`- name: DB_ADDR
  value: {{ .Values.keycloak.persistence.dbHost | quote | tpl }}`

Thanks

**Comment by unguiculus** [comment]
Configuration has changed with the latest major release. Environment variables are templated. You should be able to achive what you need.

```yaml
extraEnv: |
  DB_ADDR: {{ .Release.Name }}-postgresql
```

**Comment by unguiculus** [comment]
I assume this can be closed now.
