### ISSUE TITLE
Keycloak theme cannot be pulled from private docker registry

### ISSUE THREAD

**Issue by arjuin** [codecentric/helm-charts#237]
Hi,

Kubernetes cannot pull theme image because it's on a private registry. It could be a good idea to add imagePullSecrets field at this level:

>   extraInitContainers: |
>     - name: theme-provider
>       image: myprivateregistry.io/keycloaktheme:latest
>       imagePullPolicy: IfNotPresent
>       **imagePullSecrets:
>       - name: privateregistry**

**Comment by x-Xymos** [comment]
I use an init container with a private registry and I provide the name of the image pull secret like so: 
--set keycloak.image.pullSecrets[0]='<secret_name>'

**Comment by arjuin** [comment]
@x-Xymos this is the pullsecret for Keycloak image. Is it working even if Keycloak image is on a different repo than theme image ?

**Comment by x-Xymos** [comment]
@arjuin it does indeed, imagePullSecrets are shared across containers in a pod

**Comment by unguiculus** [comment]
Closing as solved.

**Comment by exaucae** [comment]
Should this be considered as solved? That's a workaround and it should not prevent us from having the imagePullSecrets option directly in the chart values.yml , as it has been done in #237 for your other charts.

@segtio
