### ISSUE TITLE
[keycloak] default values for keycloak.javaToolOption not working as expected

### ISSUE THREAD

**Issue by agseijas** [codecentric/helm-charts#247]
The opts that are set by default for this property  `keycloak.javaToolOption` are never applied: `-XX:+UseContainerSupport -XX:MaxRAMPercentage=50.0`  as, I'm guessing, is expected.
What it seems to be happening is that the keycloak startup scripts are already providing a JAVA_OPTS string with the heap-sizing options `-Xms` and `-Xmx` fixed to some values, which make the previous two values to always be ignored by these two JVM flags expected behaviour.

The changes were introduced here in https://github.com/codecentric/helm-charts/pull/189

So in all cases, the k8s pod memory limits are always ignored, no matter what you put there on that option, and the options like MaxRAMPercentage can actually never be used.

Maybe consider setting the full JAVA_OPTS string so that the given values can be overriden.

In general I think that what's missing is a direct way to size the keycloak's jvm, this is just an issue derived from a search on how that can be done. Only way now (and I hadn't tested it yet) is to use the `keycloak.extraEnv` and provide the JAVA_OPTS there.

BTW: Other options not conflicting with provided JAVA_OPTS are working fine.

**Comment by unguiculus** [comment]
`javaToolOption` was removed in #250. You should use `JAVA_OPTS`. Here's an example: https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/ci/postgres-ha-values.yaml#L43-L49
