### ISSUE TITLE
 Get https://codecentric.github.io/helm-charts/index.yaml: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by ludurr** [codecentric/helm-charts#255]
Hi,
i am trying to consume this github repo as helm repository, but it fails with following error:
`helm repo add codecentric https://codecentric.github.io/helm-charts

helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

Error: looks like "https://codecentric.github.io/helm-charts" is not a valid chart repository or cannot be reached: Get https://codecentric.github.io/helm-charts/index.yaml: x509: certificate has expired or is not yet valid`
thanks

**Comment by unguiculus** [comment]
This must have been a temporary issue with GitHub Pages.
