### ISSUE TITLE
Upgrade to keycloak 11.0.0

### ISSUE THREAD

**Issue by RawanS** [codecentric/helm-charts#260]
There are many new improvements and features in keycloak 11.0.0

**Comment by Hokwang** [comment]
@unguiculus by the way, when I am using v10.0.0 and then run `helm upgrade` command for v11.0.0, this chart runs upgrade command automatically? 

so I want to know there's no problem when use `helm upgrade` command simply.

**Comment by YoshieraHuang** [comment]
> @unguiculus by the way, when I am using v10.0.0 and then run `helm upgrade` command for v11.0.0, this chart runs upgrade command automatically?
> 
> so I want to know there's no problem when use `helm upgrade` command simply.

No, you first need to use `helm repo update` to update the version of this chart to v9.0.1 and then `helm upgrade` to upgrade the local release to 9.0.1.

**Comment by Hokwang** [comment]
@YoshieraHuang yes, I know how to use helm command,
but I mean that this helm chart has keycloak's internal DB upgrade process. so admin does not need to consider
upgrading keycloak v10.0.0 to v11.0.0 is no problem.

**Comment by unguiculus** [comment]
The chart does not deal with DB upgrades at all. This is handled by Keycloak itself. Please refer to Keycloaks documentation.
