### ISSUE TITLE
[keycloak] Liveness probe does not work by default

### ISSUE THREAD

**Issue by Nichts** [codecentric/helm-charts#266]
By default the admin console binds to 127.0.0.1 which causes the liveness probe to fail resulting in the pod getting killed every 5 minutes with the default liveness probe settings.

My current workaround is just setting KEYCLOAK_STATISTICS to all (this causes the bind address to change to 0.0.0.0)

**Comment by unguiculus** [comment]
Good catch. Thanks. Will have a look.

**Comment by andrew-landsverk-win** [comment]
Just noticing this as well, thanks for the workaround!
