### ISSUE TITLE
KeyCloak - Missing basepath option in new version

### ISSUE THREAD

**Issue by alesten** [codecentric/helm-charts#276]
Hey,

I currently have a keycloak instance running on version 6.0.1 (chart version 5.1.7), where there is a option to set the basepath blank. This results in the url being only the domain without `/auth/` in the end.

I am trying to create this behaviour in a new keycloak instance running version 11.0.0 (chart version 9.0.1) with the new `values.yaml` I dont have the option to set the basepath.

Is there a way I'm missing to set this basepath flag in the new values.yaml, or was it removed for something else?

**Comment by ArgTang** [comment]
@alesten Did you find a resolution for this?

**Comment by alesten** [comment]
@ArgTang I though I did by changing the `<web-context>` in `standalone-ha.xml` to just a forwardslash. But after some time there was some use-cases where this didn't work.
I ended up keeping the `/auth/` for now.
