### ISSUE TITLE
upgrade keycloak chart to v9

### ISSUE THREAD

**Issue by shaunc** [codecentric/helm-charts#278]
It looks like you've completely revised the chart values in the upgrade from v8 to v9. Are there migration/release notes anywhere?

It would seem that many values that were specified in the chart are now specified by environment variables. I still trying to figure out `keycloak.existingSecret`, `keycloak.existingSecretKey`.

Also for the database: `keycloak.persistence.existingSecretPasswordKey` and `keycloak.persistence.existingSecretUsernameKey`?

**Comment by guyromb** [comment]
+1

**Comment by unguiculus** [comment]
Please read https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#from-chart-versions--900.

Also, check out the examples in the readme which have been updated.

**Comment by unguiculus** [comment]
I assume this can be closed now.

**Comment by shaunc** [comment]
Thanks!
