### ISSUE TITLE
Is it necessary to migrate database when upgrading chart from 8.2.X to 9.0.1?

### ISSUE THREAD

**Issue by rklubenspies** [codecentric/helm-charts#280]
I had an installation using an `8.2.2` version of the chart. I created a new `values.yaml` file to migrate my database configuration into the refactored format for `9.0.1`, and then I ran `helm upgrade` to upgrade the chart to 9.0.1:

```
helm upgrade -n idp -f values-v901.yaml keycloak codecentric/keycloak --version=9.0.1
```

Keycloak's docs suggests that you must run upgrade scripts when upgrading from `v10.X` to `v11.X`. I'd assume that the server and config upgrading side is handled by containerization, but what about database migrations? Do the [database upgrade migrations](keycloak.org/docs/latest/upgrading/#_migrate_db) run automatically when upgrading the helm chart?

My Keycloak installation appears to be working normally after the upgrade, and the server info is returning Keycloak version `11.0.0` as the installation's current version—I just wanted to double-check if any other migrations or manual configuration was needed.

**Comment by guyromb** [comment]
+1

**Comment by unguiculus** [comment]
Keycloak runs database migrations automatically on startup. You should see that in the logs.
