### ISSUE TITLE
Wildcard certificated issue with ingres setup

### ISSUE THREAD

**Issue by orefalo** [codecentric/helm-charts#281]
The following line is creating an issue with my configuration. I use a wild certificate in my cluster, directly configured within the nginx-ingress. If I specify a secret on the tls, the wild cert won't be picked up.

https://github.com/codecentric/helm-charts/blob/2bb6f928bc3a78cc5accde8f15b5558510f630fa/charts/keycloak/templates/ingress.yaml#L26

I think if would be better to add a {{ if }} enclosure

**Comment by unguiculus** [comment]
@orefalo Please verify the fix.

**Comment by orefalo** [comment]
works than kyou
