### ISSUE TITLE
handy values entries to set keycloak admin login/password

### ISSUE THREAD

**Issue by orefalo** [codecentric/helm-charts#282]
Maybe some handy entries to setup admin login/password would help...
  Kind of.. a must have if you ask me.

https://github.com/codecentric/helm-charts/blob/2bb6f928bc3a78cc5accde8f15b5558510f630fa/charts/keycloak/values.yaml#L99

old chart had those handy entries

```
  ## Username for the initial Keycloak admin user
  username: admin

  ## Password for the initial Keycloak admin user. Applicable only if existingSecret is not set.
  ## If not set, a random 10 characters password will be used
  #password: ""

  # Specifies an existing secret to be used for the admin password
  existingSecret: "keycloak-http"

  # The key in the existing secret that stores the password
  existingSecretKey: password
```

**Comment by unguiculus** [comment]
Please checkout the readme. The examples have been updated:

* https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#creating-a-keycloak-admin-user
* https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#from-chart-versions--900

You may also want to have a look at the test values for CI:
https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/ci/postgres-ha-values.yaml

Does this help?

**Comment by orefalo** [comment]
It does, I eventually got it.

Keycloak can't be used without setting an admin login/password - it's quite an important setting if you ask me.
so even if it's commented out, my recommendation is to add the description in chart values.
   if you have it for the DB... why not the most important setting of them all?

My 2c..

**Comment by orefalo** [comment]
It does, I eventually got it.

Keycloak can't be used without setting an admin login/password - it's quite an important setting if you ask me.
so even if it's commented out, my recommendation is to add the description in chart values.
   if you have it for the DB... why not the most important setting of them all?

My 2c..
