### ISSUE TITLE
Disable keycloak welcome page

### ISSUE THREAD

**Issue by reste85** [codecentric/helm-charts#29]
Hi guys, 
is there a way to disable the Keycloak welcome page?

Thank you!

**Comment by akkie** [comment]
https://developer.jboss.org/thread/242941

**Comment by unguiculus** [comment]
You can do this with a custom CLI script using `keycloak.cli.custom`.

**Comment by akkie** [comment]
@unguiculus Thanks for this hint :+1: 

I've created a `custom.cli` file which I deploy with a custom keycloak docker image.
```
/subsystem=undertow/server=default-server/host=default-host/location=\/:remove
```
The file is located in /opt/jboss/tools/cli/custom.cli. But if I add this script, keycloak will not start anymore.

```
08:55:17,571 INFO [org.jboss.modules] (CLI command executor) JBoss Modules version 1.9.0.Final
08:55:17,650 INFO [org.jboss.msc] (CLI command executor) JBoss MSC version 1.4.5.Final
08:55:17,701 INFO [org.jboss.threads] (CLI command executor) JBoss Threads version 2.3.3.Final
08:55:17,867 INFO [org.jboss.as] (MSC service thread 1-1) WFLYSRV0049: Keycloak 6.0.1 (WildFly Core 8.0.0.Final) starting
08:55:17,952 INFO [org.jboss.vfs] (MSC service thread 1-1) VFS000002: Failed to clean existing content for temp file provider of type temp. Enable DEBUG level log to find what caused this
08:55:18,747 INFO [org.wildfly.security] (ServerService Thread Pool -- 8) ELY00001: WildFly Elytron version 1.8.0.Final
08:55:19,429 INFO [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/core-service=management/management-interface=http-interface' is deprecated, and may be removed in a future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
08:55:19,537 INFO [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/subsystem=undertow/server=default-server/https-listener=https' is deprecated, and may be removed in a future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
08:55:19,680 INFO [org.jboss.as.patching] (MSC service thread 1-2) WFLYPAT0050: Keycloak cumulative patch ID is: base, one-off patches include: none
08:55:19,689 WARN [org.jboss.as.domain.management.security] (MSC service thread 1-2) WFLYDM0111: Keystore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
08:55:19,796 INFO [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
08:55:19,803 INFO [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Keycloak 6.0.1 (WildFly Core 8.0.0.Final) started in 2218ms - Started 64 of 78 services (25 services are lazy, passive or on-demand)
Node path format is wrong around 'opt' (index=1).
08:55:19,944 INFO [org.jboss.as] (MSC service thread 1-1) WFLYSRV0050: Keycloak 6.0.1 (WildFly Core 8.0.0.Final) stopped in 18ms
```

I think the main error is `Node path format is wrong around 'opt' (index=1).`. But `opt` doesn't exists in my script

**Comment by akkie** [comment]
Sorry, my fault! The `keycloak.cli.custom` property needs the commands directly passed instead of a file.

**Comment by akkie** [comment]
After digging a bit deeper into this issue. It seems that the command `/subsystem=undertow/server=default-server/host=default-host/location=\/:remove` disables only the `/opt/jboss/keycloak/welcome-content` page, which contains only a redirect to the `/auth` path.

The "Welcome to Keycloak" page cannot be disabled but it can be themed. The default theme is located in `/opt/jboss/keycloak/themes/keycloak/welcome`. It can be set by setting the environment variable `KEYCLOAK_WELCOME_THEME` or by setting the following XML in the `keycloak-server` subsystem in the `/opt/jboss/keycloak/standalone/configuration/standalone.xml` file:
```xml
<theme>
    ...
    <welcomeTheme>${env.KEYCLOAK_WELCOME_THEME:keycloak}</welcomeTheme>
    ...
</theme>
```

**Comment by ayoub96anbara** [comment]
> After digging a bit deeper into this issue. It seems that the command `/subsystem=undertow/server=default-server/host=default-host/location=\/:remove` disables only the `/opt/jboss/keycloak/welcome-content` page, which contains only a redirect to the `/auth` path.
> 
> The "Welcome to Keycloak" page cannot be disabled but it can be themed. The default theme is located in `/opt/jboss/keycloak/themes/keycloak/welcome`. It can be set by setting the environment variable `KEYCLOAK_WELCOME_THEME` or by setting the following XML in the `keycloak-server` subsystem in the `/opt/jboss/keycloak/standalone/configuration/standalone.xml` file:
> 
> ```
> <theme>
>     ...
>     <welcomeTheme>${env.KEYCLOAK_WELCOME_THEME:keycloak}</welcomeTheme>
>     ...
> </theme>
> ```

what is the value that I should pass to KEYCLOAK_WELCOME_THEME to disable The "Welcome to Keycloak" page 
PS: I use keycloak docker image

**Comment by ayoub96anbara** [comment]
I found the solution for  keycloak docker image: [solution](https://keycloak.discourse.group/t/completely-disable-landing-page-at-auth/6027/7?u=ayoub96anbara)
