### ISSUE TITLE
Keycloak extraEnv/extraEnvFrom type mismatch

### ISSUE THREAD

**Issue by keeganwitt** [codecentric/helm-charts#293]
_values.schema.json_ specifies the type of `extraEnv` and `extraEnvFrom` to be `string`, and the defaults in _values.yaml_ are `""`.  However, the docs show this as taking in an array, and the values in _values-production.yaml_, _h2-values.yaml_, and _postgres-ha-values.yaml_ are all using an array type, not a string type.

I think _values.yaml_ should have defaults of `[]` and the schema should be changed to type `array`.

**Comment by keeganwitt** [comment]
Ah, I see now I actually got confused between extraEnv for the subchart.  I suggest changing the documentation.  It says of the admin user creation "Please refer to the section on database configuration for how to configure a secret for this."  But in the database values, it's an array, not a string, and the admin user creation actually needs to be a string.

**Comment by unguiculus** [comment]
> Please refer to the section on database configuration for how to configure a secret for this.

This section shows how to create a secret. Instead of repeating things it just refers to this section. The same principles apply for creating a secret for the admin user.

> Additionally, h2-values.yaml and postgres-ha-values.yaml seem to be referencing the Keycloak admin user, but using it as the DB root user.

This is not the case. These files configure a Keycloak admin user.

**Comment by eigood** [comment]
I have this problem too; I have postgresql.enabled=false, as I have a shared postgresql database for my cluster.  I'm then trying to configure DB_* values, as I see them in keycloak/statefulset.yaml.  Because extraEnv is required to be a string, I can't do that, however.

**Comment by eigood** [comment]
I see in the docs, where these are supposed to be strings.  This is very bad form; an anti-pattern.

**Comment by Lirt** [comment]
Apparently it should be used in this form (example):

```yaml
extraEnv: |
  - name: PROXY_ADDRESS_FORWARDING
    value: 'true'
```

**Comment by unguiculus** [comment]
@eigood This is not bad practice. It is done so values can be templated using `tpl`. As a solution, you could introduce custom values and reference them.

Example:

```yaml

myDbUser: username

extraEnv: |
  - name: DB_USER
    value: {{ .Values.myDbUser }}
```

Instead of setting `myDbUser` in the values file, you could also pass it using `--set-string myDbUser=myuser`.
