### ISSUE TITLE
Keycloak - Looking for clarification on what data is safe to change in the Web UI

### ISSUE THREAD

**Issue by ubergeek77** [codecentric/helm-charts#294]
Based on the ReadMe for the Keycloak Helm Chart, unless I am mistaken, it seems things such as Realms and custom themes are *not* safe to create or modify through the Web UI. Adding them through the Web UI is not proposed as an option in the ReadMe, so I take it that importing at least Realms and Themes are hard requirements when running this chart.

I'm new to Keycloak (trying to learn it through this Chart), but the official Keycloak documentation isn't very clear on *where* information on certain things is stored - I don't know what qualifies as "metadata," so I'm not sure which components of Keycloak get stored in the database vs in the Infinispan cache. In other words, I don't know if *all* Realm information is stored in the Infinispan cache, or if some of it persists in the database. I'm trying to be careful about what I modify that gets stored in the cache, as it seems this chart does not yet replicate information stored there:

https://github.com/codecentric/helm-charts/issues/214

Because of these considerations, I'm not sure what parts of the Web UI are "not safe to touch" when running this chart. Am I mistaken, and everything is safe to configure? Or are there certain elements that are indeed not safe to change in the Web UI?

As someone not inherently familiar with Keycloak but wanting to learn, I would greatly appreciate some distinctions between "what you may change in the Web UI" and "what ***you may not change*** in the Web UI" in the context of running this Helm Chart.

Thanks!

**Comment by unguiculus** [comment]
Your question is not really an issue with this chart but with Keycloak itself. Anything you change in the UI is stored in the database.
