### ISSUE TITLE
How does ingress in keycloak incorporate istio

### ISSUE THREAD

**Issue by muyang3121** [codecentric/helm-charts#297]
I am currently experimenting with the use of ISTIO and Keycloak, but I don't know how to modify the Ingress of Keycloak. Can you give me some guidance?In addition, does ISTIO support keycloak's default Ingress? Please let me know how to do it. Thank you very much!

**Comment by Bengreen** [comment]
we have integrated keycloak with istio and utilised istios gateway and virtualservice to provision an ingress that way. Then istio can see all traffic coming in towards keycloak. it works very well and is relatively simple to configure. So in that case we disable the ingress definition of keycloak.
Might be an option to consider.

**Comment by Rjvs** [comment]
@Bengreen any documentation of what you did?

**Comment by Bengreen** [comment]
No i dont have any documentation on this. This was done using GKE. But our approach was:
1. Create a manifest for istioctl that describes a gateway LB that you want to utilise.(provide the IP address of the desired IP you want the gateway to create and use when deployed). This is for deploying your istio operator. You will see a gatewayd pod created as well as your istiod.
2. Now create istio gateway resources to expose your http services to the gateway LB your created above. At this point you need to assign your DNS name refrence the gateway instance and optionally add TLS certs. (you can serve multiple DNS records via a single gateway). NOTE: be careful here if you use certificates. browsers are overly aggressive doing connection sharing where they see a single TLS certificate and direct all traffic (for different hosts) onto a single connection (even though they are identified as seperate hosts). You will get 404 messages here if you are not careful.
3. Now create virtualservices to describe your services composed on the http paths that you want to connect to your gateway resources. e.g. /auth/ -> service and port of your keycloak instance.
You should now be able to go to your browser and access your keycloak instance via https://<DNS NAME>/auth/
