### ISSUE TITLE
Keycloak chart 9.0.7 not working under https

### ISSUE THREAD

**Issue by codependent** [codecentric/helm-charts#303]
I've deployed the latest version of the Keycloak chart:

```
helm install keycloak codecentric/keycloak --set ingress.enabled=true --set ingress.rules[0].host=myhost.io --set ingress.rules[0].paths={/} --set ingress.tls[0].hosts={myhost.io}  --namespace=lab
```

When everything is up and running I access https://myhost.io. After setting the admin user and password I try to access the admin console: https://myhost.io/auth/admin/master/console/

However the browser never loads the page since the load of the keycloak.js file is interrupted. It is trying to get it from http:// and given the browser URL is https it blocks that content.

Source of the https://myhost.io/auth/admin/master/console/ page, showing that the keycloak.js resource is gotten using http.

```
    <script src="/auth/resources/9dhzl/common/keycloak/lib/ui-ace/min/ace.js"></script>
    <script src="/auth/resources/9dhzl/common/keycloak/lib/ui-ace/ui-ace.min.js"></script>

    <script src="http://myhost.io/auth/js/keycloak.js?version=9dhzl" type="text/javascript"></script>
```
Is there anything missing in the chart to make it work with https o is it a Keycloak problem?

**Comment by unguiculus** [comment]
You might have to add annotations depending on the ingress controller you use. Also, you did not specify a TLS secret.

**Comment by codependent** [comment]
Regarding the secret, I have configured the nginx ingress controller to use a default secret, no problem there. Regarding the annotations I’ll have a look at them. Oddly enough it works without anything else up to chart version 8.3.0.

**Comment by unguiculus** [comment]
There was an issue with the TLS cert (#281, #288) always being added which has been fixed.

**Comment by codependent** [comment]
Thanks for letting me know. Any idea when the fix will be released?

**Comment by unguiculus** [comment]
It has already been released.

**Comment by codependent** [comment]
I thought this problem was solved but after trying again with both chart versions 9.0.8 and 9.1.0 it still happens:

A clean installation with 9.1.0...
```
helm install keycloak codecentric/keycloak --set ingress.enabled=true --set ingress.rules[0].host=lab.x.io --set ingress.rules[0].paths={/} --set ingress.tls[0].hosts={lab.x.io} --namespace=lab
```
...creates an ingress like this (notice I don't specify a tls secret since the nginx controller has a default one configured):
```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    creationTimestamp: "2020-09-12T09:51:26Z"
    finalizers:
    - networking.gke.io/ingress-finalizer-V2
    generation: 1
    labels:
      app.kubernetes.io/instance: keycloak
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: keycloak
      app.kubernetes.io/version: 11.0.2
      helm.sh/chart: keycloak-9.1.0
    name: keycloak
    namespace: lab
    resourceVersion: "8403172"
    selfLink: /apis/extensions/v1beta1/namespaces/lab/ingresses/keycloak
    uid: b0e142da-5306-4f03-8fd0-b1f4914d7ba3
  spec:
    rules:
    - host: lab.x.io
      http:
        paths:
        - backend:
            serviceName: keycloak-http
            servicePort: http
          path: /
    tls:
    - hosts:
      - lab.x.io
  status:
    loadBalancer:
      ingress:
      - ip: x.x.x.x
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

I use port forwarding to setup the initial admin password and access /auth/admin/master/console/. The browser keeps blocking the page since the keycloak.js resource is gotten from http. Also notice  the following http Javascript variables:

```
    <script type="text/javascript">
        var authServerUrl = 'http://lab.x.io/auth';
        var authUrl = 'http://lab.x.io/auth';
        var consoleBaseUrl = '/auth/admin/master/console/';
        var resourceUrl = '/auth/resources/hhz2x/admin/keycloak';
        var masterRealm = 'master';
        var resourceVersion = 'hhz2x';
    </script>
   ...
   <script src="http://lab.x.io/auth/js/keycloak.js?version=hhz2x" type="text/javascript"></script>
```

Other applications I have running under a similar ingress correctly detect https requests, setting urls in web resources correctly with https. What could be the problem here?

**Comment by codependent** [comment]
I've setup debug in the nginx ingress controller to verify that the correct headers are being propagated and everything seems to be fine (it incluides `X-Forwarded-Proto: https`):

```
2020/09/12 10:25:40 [debug] 36#36: *525 http proxy header:
"GET /auth/admin/master/console/ HTTP/1.1
Host: lab.x.io
X-Request-ID: 6753a6f8438f416a93adb2cdd08c5cf0
X-Real-IP: 10.7.0.8
X-Forwarded-For: 10.7.0.8
X-Forwarded-Host: lab.x.io
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Scheme: https
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:80.0) Gecko/20100101 Firefox/80.0
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
accept-language: es-ES,en-US;q=0.7,en;q=0.3
accept-encoding: gzip, deflate, br
upgrade-insecure-requests: 1
```

**Comment by genbutsu** [comment]
The main problem is that you need to add this ENVIRONMENT variable:

extraEnv: |
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"

This will close the isuses, and you can login to manage a realm.

However then there will be second problem: while logging into an application it will redirect during login to HTTP instead of HTTPS

**Comment by codependent** [comment]
@genbutsu thanks for the info, I missed that envar from the Keycloak Dockerfile info. It solved my issue.
