### ISSUE TITLE
DB credentials not added to chart generated secret

### ISSUE THREAD

**Issue by aleksanderaleksic** [codecentric/helm-charts#304]
Chart version: 9.1.0
Helm version: 3.2.4
Kubernetes version: 1.18.6

Hi, I'm having issues with the keycloak chart not being able to store the values for the secret keys`DB_USER` and `DB_PASSWORD`

My `values.yaml` looks like this:
``` 
keycloak:
  postgresql:
    enabled: false

  extraEnv: |
    - name: DB_VENDOR
      value: postgres
    - name: DB_ADDR
      value: postgres.db.com
    - name: DB_PORT
      value: "25060"
    - name: DB_DATABASE
      value: keycloak

  extraEnvFrom: |
    - secretRef:
        name: '{{ include "keycloak.fullname" . }}-db'

  secrets:
    db:
      stringData:
        DB_USER: '{{ .Values.secrets.db.username }}'
        DB_PASSWORD: '{{ .Values.secrets.db.password }}'

secrets:
  db:
    username: keycloak
    password: 1234
```
(Of course, the secrets are not going to be in the `values.yaml`, it's just for the simplicity)

Im running this command: `helm upgrade --install keycloak . -f values.yaml`

When I check the output of the secret I get the result below, but `DB_PASSWORD` and `DB_USER` are empty.
```
apiVersion: v1
data:
  DB_PASSWORD: ""
  DB_USER: ""
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: keycloak
    meta.helm.sh/release-namespace: keycloak
  creationTimestamp: "2020-09-11T19:26:59Z"
  labels:
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/version: 11.0.2
    helm.sh/chart: keycloak-9.1.0
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:DB_PASSWORD: {}
        f:DB_USER: {}
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:type: {}
    manager: Go-http-client
    operation: Update
    time: "2020-09-11T19:26:59Z"
  name: keycloak-db
  namespace: keycloak
  resourceVersion: "3547169"
  selfLink: /api/v1/namespaces/keycloak/secrets/keycloak-db
  uid: 928d63b3-1958-4588-8b18-8a68ab9363b1
type: Opaque
```
I have also tried using the `--set-string secrets.db.password=1234` flag with no luck

any idea of what might be wrong?

**Comment by unguiculus** [comment]
Starting with v9.0.0, values are no longer nested under `keycloak`. So, the only thing that's recognized in your example is this:

```yaml
secrets:
  db:
    username: keycloak
    password: 1234
```

This causes the secret to be created but since no `stringData`  is set, it is empty.

See example in the readme: https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#using-a-secret-managed-by-the-chart

Also, please see: https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#from-chart-versions--900

**Comment by aleksanderaleksic** [comment]
@unguiculus I have keycloak as a dependency of my chart so I have to use `keycloak` in the `values.yaml`.
Also if I add `DB_USER` and `DB_PASSWORD` to the `extraEnv` it works.  
One thing to also keep in mind is that the secret named `keycloak-db` is created whit the data:
```
data:
  DB_PASSWORD: ""
  DB_USER: ""
```
So I don't think its the structure in the `values.yaml` that's the issue.

**Comment by aleksanderaleksic** [comment]
I figured it out. 
The reason was that I misunderstood the scope of the dependency values.
So instead of:
```
keycloak:
   secrets:
       db:
         stringData:
           DB_USER: '{{ .Values.secrets.db.username }}'
           DB_PASSWORD: '{{ .Values.secrets.db.password }}'

secrets:
   db:
      username: keycloak
      password: 1234
```

But technically it should have been like this:
```
keycloak:
   secrets:
       db:
         username: keycloak
         password: 1234
         stringData:
           DB_USER: '{{ .Values.secrets.db.username }}'
           DB_PASSWORD: '{{ .Values.secrets.db.password }}'
```
Since helm cannot access the values outside of the `keycloak` scope.
