### ISSUE TITLE
proxy schema support as in older charts: application url not authorized

### ISSUE THREAD

**Issue by genbutsu** [codecentric/helm-charts#307]
older releases of the chart, helps to manage Keycloak via Ingress to manage proxy schema

> // WildFly CLI configurations. They all end up in the file 'keycloak.cli' configured in the configmap whichn is
> // executed on server startup.
>   cli:
> [..]
>     reverseProxy: |
>       /socket-binding-group=standard-sockets/socket-binding=proxy-https:add(port=443)
>       /subsystem=undertow/server=default-server/http-listener=default:write-attribute(name=redirect-socket, value=proxy-https)
>       /subsystem=undertow/server=default-server/http-listener=default:write-attribute(name=proxy-address-forwarding, value=true)
> "

Actually I could manage to set up it working under proxy with environment variable, but it doesn't manage HTTPS as schema as in old chart annotation: is there a way to manage it in the new chart? or via environment variable?

The problems happens when keycloak receives a forwarded user from an HTTPS application: if the application URL to get back is HTTPS it will not authorize that, because the forwared schema keycloak receives is HTTP and doesn't match the one authorized in the realm configuration that is HTTPS. It is a production only problem, it has no problem in pre-production with http protocol.

thanks :-)

**Comment by unguiculus** [comment]
Please try the following:

You need to set PROXY_ADDRESS_FORWARDING as documented at https://github.com/keycloak/keycloak-containers/tree/master/server#enabling-proxy-address-forwarding. 

You can still add custom startup scripts (see https://github.com/keycloak/keycloak-containers/tree/master/server#running-custom-scripts-on-startup) to reconfigure WildFly.

Please try the following:


```yaml
extraEnv: |
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"

startupScripts:
  reverseProxy.cli: |
    embed-server --server-config=standalone-ha.xml --std-out=echo
    batch
    /socket-binding-group=standard-sockets/socket-binding=proxy-https:add(port=443)
    /subsystem=undertow/server=default-server/http-listener=default:write-attribute(name=redirect-socket, value=proxy-https)
    run-batch
    stop-embedded-server
```

**Comment by unguiculus** [comment]
I think, setting `PROXY_ADDRESS_FORWARDING` should be everything you need.

See also #303.
