### ISSUE TITLE
How to specify JDBC parameters using --set

### ISSUE THREAD

**Issue by ivangfr** [codecentric/helm-charts#31]
Hi,

For instance, when I run a simple keycloak docker container, I can inform the `JDBC_PARAMS` environment variable like:
```
docker run --name keycloak -e DB_VENDOR=postgres -e JDBC_PARAMS='useSSL=false' jboss/keycloak
```

Keycloak Helm Chart provides the `keycloak.extraEnv`

Using a config file it would be something like this right?
```
keycloak:
  extraEnv: |
    - name: JDBC_PARAMS
      value: useSSL=false
```

What about using `--set`? I've tried something like
```
...
--set keycloak.extraEnv[0].name=JDBC_PARAMS,keycloak.extraEnv[0].value=useSSL=false
...
```

But, it doesn't work.

I am using
```
$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

The `--set` config, I am following https://github.com/helm/helm/blob/master/docs/using_helm.md#the-format-and-limitations-of---set

Thanks!

**Comment by unguiculus** [comment]
`extraEnv` must be set as a string while you're trying to set it as a YAML list. I never tried to set that with the `--set` flag. Not sure if that works. Any reason why you don't use a values file?

**Comment by ivangfr** [comment]
Hi @unguiculus It's just curiosity. In the script that I have, I've written all `helm install`s using `--set`. That is why I'd like to keep using it and don't change to a value file, just because of the need in Keycloak chart. Besides, I think it is clearer to use `--set` when the number of properties you need to change is around 3 or 4. Thanks!

**Comment by unguiculus** [comment]
I'm closing this issue now. The functionality is needed an won't change. You should switch to a values file in this case which is IMO preferable anyways. There are other limitations of the `--set` flag as well which are not related to this chart.
