### ISSUE TITLE
Startup script volume overwrites the existing scripts in custom Docker image

### ISSUE THREAD

**Issue by hisener** [codecentric/helm-charts#310]
As [Keycloak docker image documentation](https://github.com/keycloak/keycloak-containers/blob/master/server/README.md#running-custom-scripts-on-startup) suggests, we created a custom docker image with our common scripts for all environments. However, this doesn't work well with `codecentric/keycloak` Helm chart since [the volume mount](https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/templates/statefulset.yaml#L130-L135) overwrites the existing scripts.

**Steps to reproduce**

1. Create a custom image with custom scripts.
```Dockerfile
FROM jboss/keycloak:11.0.2

COPY custom-scripts/ /opt/jboss/startup-scripts/
```

2. Change Keycloak image repository and tag to use the custom image.

```
image:
  repository: <your_repo>
  tag: <your_tag>
```

3. Apply changes and check `/opt/jboss/startup-scripts` folder. It contains `keycloak.cli` from Helm chart.

**Workaround**

A workaround would be moving [`scripts/keycloak.cli`](https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/scripts/keycloak.cli) to `custom-scripts/` and setting `startupScripts` to `null`. But this is not ideal and prone to errors while upgrading the Helm chart. Also, it prevents using `startupScripts` option, which is very useful for some configurations that differ from environment to environment.

```
image:
  repository: <your_repo>
  tag: <your_tag>

startupScripts: null
```

**Comment by unguiculus** [comment]
Thanks for raising this. I'd say your workaround is fine. The Helm chart tries to not be opinionated. That's why all the WildFly configuration stuff from previous versions has been removed. Don't expect any changes here. That being said, I guess a solution could be mounting the script to a different location and then copying it to `/opt/jboss/startup-scripts` on startup. However, that would require adding a custom start script which I wanted to avoid.

**Comment by hisener** [comment]
I don't think the workaround is fine because then we cannot use `startupScripts`. It's quite useful for environment-specific configurations. Do you think it's feasible to mount each script separately so that we can use `subPath` and won't overwrite existing ones from docker image?

**Comment by unguiculus** [comment]
I thought you don't need the `startupScripts` option because you already have the scripts in your custom image? Do you need both?

Using a `subPath` actually sounds like a good idea. I'll look into that.

**Comment by hisener** [comment]
> I thought you don't need the `startupScripts` option because you already have the scripts in your custom image? Do you need both?

Sorry, I wasn't clear. I want to put common scripts to a custom image (by copying into `/opt/jboss/startup-scripts/`) and use `startupScripts` for environment-specific scripts.

**Comment by CalamarBicefalo** [comment]
Sorry, but I do not understand how subpath works and the docs don't mention this specifically @unguiculus.

So in @hisener 's case. With this new commit that got merged, how would the resulting values.yml look like so helm does not override your custom scripts but the keycloak.cli is preserved?
