### ISSUE TITLE
[codecentric/keycloak] Extend README for mapping AKS external IP with DNS, setting up HTTPS

### ISSUE THREAD

**Issue by Shruti-R** [codecentric/helm-charts#317]
I have AKS cluster on which I am trying to setup Keycloak with helm charts. However, I could not find any documentation on below:
- Map external IP with DNS
- Create certs & enable HTTPS
- Enable different [operating modes](https://www.keycloak.org/docs/latest/server_installation/index.html#_operating-mode) of Keycloak
- Access embedded database like Postgres on external IP

**Comment by unguiculus** [comment]
Keyclok is always run in standalone mode. Anything else doesn't make sense on Kubernetes. The other issue you mentioned are not really specific to this chart. Please refer to Keycloak docs, Kubernetes docs, or docs on the Bitnami Postgres chart.
