### ISSUE TITLE
Postgres running as root

### ISSUE THREAD

**Issue by verwilst** [codecentric/helm-charts#32]
When enabling postgres, the pod fails when Podsecuritypolicies are in effect on the cluster:

Events:
  Type     Reason     Age               From                                             Message
  ----     ------     ----              ----                                             -------
  Normal   Scheduled  26s               default-scheduler                                Successfully assigned keycloak/keycloack-postgresql-844b466bd5-784b4 to k8s003-worker003
  Normal   Pulling    26s               kubelet, k8s003-worker003  Pulling image "postgres:9.6.2"
  Normal   Pulled     18s               kubelet, k8s003-worker003  Successfully pulled image "postgres:9.6.2"
  Warning  Failed     4s (x3 over 18s)  kubelet, k8s003-worker003  Error: container has runAsNonRoot and image will run as root
  Normal   Pulled     4s (x2 over 17s)  kubelet, k8s003-worker003  Container image "postgres:9.6.2" already present on machine

**Comment by unguiculus** [comment]
That's an issue with the Postgres chart that can't be fixed here.

**Comment by verwilst** [comment]
You're depending on a very old version of postgresql, which kind of does make it fixable here. 😉 The latest version of the postgresql role supports running as non root.
