### ISSUE TITLE
Help with keycloak not recognizing https redirects

### ISSUE THREAD

**Issue by RAbraham** [codecentric/helm-charts#33]
Hi,

Thanks for this chart. I'd appreciate any help you can guide me with. My issue is that even though I specify a redirect url as `https://myclient/oidc_callback`, when the actual redirect happens, it fails as it redirects to `http` instead of `https` i.e. `http://myclient/oidc_callback`.

My keycloak service(and client) are exposed via ingress using an NGINX controller.

I see `PROXY_ADDRESS_FORWARDING` is set as true as default but it still does not work for me.

Questions:
- Is there any setting I can modify in `values.yaml` to make this work? 
- This [SO questions](https://stackoverflow.com/questions/32084604/why-is-keycloak-removing-the-ssl-in-the-redirect-uri) making changes to an XML file. Do you know how I can have access to them on the pod or can I upload a file?
- If you have any other suggestions on how you made it work, I'd be very grateful.

**Comment by RAbraham** [comment]
I managed to look up the standalone.yaml file and found this setting
```
        <socket-binding name="https" port="${jboss.https.port:8443}"/>
```
Can I assume that `jboss.https.port` is set to `443`?

**Comment by RAbraham** [comment]
I found out that it's `8443` that's open on the pod and not `443`. If you don't mind, could you show me how you set up your ingress/service so that it routes it correctly to `8443` port on the pod? I modified the keycloak-http service to add a 443 port but that didn't work either.  I'd be very grateful for any help you can afford.

**Comment by tsbatista** [comment]
I have hit what seems to be this issue on a pre production environment when upgrading from the stable charts, from the chart version keycloak-4.10.1 to the chart version keycloak-4.14.0. Not sure what changed in between these two releases but this completely broke my access to every web client, including the administration console.

My instance is deployed on gke with cert-manager as the ssl certificates for the default google ingress.
I can try to debug the problem on that environment if you want, but I need to know what I am looking for, so I would love some pointers from the chart maintainers as to what I should look for

**Comment by RAbraham** [comment]
@tsbatista Thank you very much for your offer! I found out that it could be my client issue and not necessarily a keycloak issue(I hope!). I'm working on that currently. I'm still keeping this ticket open as I'm not entirely sure but I feel that you may have another problem and it's worthy of it's own ticket?

**Comment by tsbatista** [comment]
Ok, close this and I will get back to it once I figure out what really broke my instance. If the problem is with the chart the I will open a new issue

**Comment by RAbraham** [comment]
My issue was on the client side. Sorry for the confusion.
