### ISSUE TITLE
[keycloak] Add possiblity to declare multiple ingresses

### ISSUE THREAD

**Issue by olivierboudet** [codecentric/helm-charts#335]
This is a feature request.

Today it is possible to declare only one ingress to expose keycloak.
For security purpose, I want to have two ingresses : 
- one for exposing keycloak publicly
- one for exposing admin console

The second ingress would have annotation `nginx.ingress.kubernetes.io/whitelist-source-range` and path `/auth/admin/?.*`

Would it be possible to have a `ingresses` array around the current ingress declaration ?

**Comment by unguiculus** [comment]
That would certainly make sense.

**Comment by olivierboudet** [comment]
Is #406 makes sense ? I choose to have an explicit part in values to create an ingress for admin console. I think it is more understandable than having an array for multiple ingresses or something too generic.

**Comment by mircohaug** [comment]
closed by PR
