### ISSUE TITLE
[Keycloak] DB initialization & migration

### ISSUE THREAD

**Issue by Baklap4** [codecentric/helm-charts#336]
Currently the database migration of Keycloak happens while the pod starts. However if an healthcheck is added with an initialdelay of let's say 10 seconds the deployment of keycloak will fail. This is due to not being live at that moment of time. Is there any chance initialization and migration will be added as separate hooks which can be ran during pre-upgrade phase? This way the hook will fire first (without any healthchecks going on) so the application can correctly migrate the db. I'd propose 2 hooks, one for initializing and the other for seeding the database.

**Comment by Baklap4** [comment]
Any update aside from the bot?

**Comment by Baklap4** [comment]
It's been a while....

**Comment by mircohaug** [comment]
Hi, do i understand you correctly that you would prefer a liveness/readyness probe with a low `initialDelaySeconds`? Without further investigation it seems possible to do the database migration in an additional init container.

**Comment by jonkerj** [comment]
I may be wrong, but I think this can be solved by bumping the version of the postgresql subchart to [at least 10.3.0](https://github.com/bitnami/charts/commit/bc9ad41dfc5cf864c2f3d90a206c54c4268f0311): it bundles an (optional) startupProbe. This probe is to prevent using `initialDelaySeconds` to survive long startup times.

**Comment by jonkerj** [comment]
I forked the repo to PR this. I bumped the sub-chart, changed the postgres fullname template in `_helpers.tpl`, but as the bundled postgres quite old, the new statefulset contains all kinds of changes other than `replicas`, `template` and `updateStrategy`, so in order to upgrade, you'll have to delete the StatefulSet before helm-upgrading.

**Comment by MrKrabat** [comment]
Well, my organization will be moving to the bitnami keycloak helm chart.
I think this is generally a good move, as Bitnami is known for its security-oriented charts and docker images.

**Comment by jonkerj** [comment]
Not stale, still working on it. Reviewing my PR seems to require more time than the stale timeout allows for 😝
