### ISSUE TITLE
can Keycloak be configured via cli commands on startup

### ISSUE THREAD

**Issue by Bengreen** [codecentric/helm-charts#338]
Is there an option and examples for configuring Keycloak via cli commands on startup.

e.g. creating a realm and add a client?

I looked at startupScripts but was unable to make the leap to seeing if/how I could use this to configure a client?

**Comment by wdesplas** [comment]
Hi,
You can maybe refer to https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#setting-a-custom-realm

Hope this will help

**Comment by Bengreen** [comment]
i already do that part with being able to load the config via json and this is pretty good. But for a specific example we end up with a json file that is larger than that supported by our secrets management system.  (NOTE we are generating this json file by exporting the keycloak config to json).

So i wanted to be able to pull in a much reduced file as a secret (with minimal configuration info).
Then to run a script that would parse that config file and generate  json or stream of commands that can be used to apply the config to keycloak.

**Comment by klg71** [comment]
Maybe this could help you: https://github.com/klg71/keycloakmigration you can define your keycloak configuration through yaml and migrate it through an extraContainer.

**Comment by unguiculus** [comment]
Terraform would be a good fit for that:
https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs

**Comment by Morriz** [comment]
@Bengreen we do this already by building an [openapi client]() from keycloak and using that in our [task runner](redkubes/otomi-tasks/blob/master/src/tasks/keycloak/keycloak.ts).

I suggest looking at the entirety of otomi.io.

**Comment by Morriz** [comment]
> Terraform would be a good fit for that:
> https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs

I find that the wrong approach to solving api transactions personally.
