### ISSUE TITLE
Startup script not executed

### ISSUE THREAD

**Issue by MansurEsm** [codecentric/helm-charts#341]
I try to secure the admin access to keycloak as following:

`chart:
    git: https://github.com/codecentric/helm-charts.git
    path: charts/keycloak
    ref: keycloak-9.5.0
[...]
startupScripts: 
      restrict_port.cli: |
        embed-server --server-config=standalone.xml --std-out=echo
        /socket-binding-group=standard-sockets/socket-binding=admin-port/:add(port=${jboss.http.port:9991})
        /subsystem=undertow/server=default-server/http-listener=admin-port:add(socket-binding=admin-port, enable-http2=true)
        /subsystem=undertow/configuration=filter/expression-filter=portAccess:add(,expression="path-prefix('/auth/admin') and not equals(%p, 9991) -> response-code(403)")
        /subsystem=undertow/server=default-server/host=default-host/filter-ref=portAccess:add()
        stop-embedded-server
      mystartup.sh: |
        #!/bin/sh
        echo 'Hello from my custom startup script!'`

Shell into the pod ...

`[jboss@login-netzebw-keyclo-0 ~]$ cat /opt/jboss/keycloak/standalone/configuration/standalone.xml | grep "socket-binding-group" -A 15
    <socket-binding-group name="standard-sockets" default-interface="public" port-offset="${jboss.socket.binding.port-offset:0}">
        <socket-binding name="management-http" interface="management" port="${jboss.management.http.port:9990}"/>
        <socket-binding name="management-https" interface="management" port="${jboss.management.https.port:9993}"/>
        <socket-binding name="ajp" port="${jboss.ajp.port:8009}"/>
        <socket-binding name="http" port="${jboss.http.port:8080}"/>
        <socket-binding name="https" port="${jboss.https.port:8443}"/>
        <socket-binding name="txn-recovery-environment" port="4712"/>
        <socket-binding name="txn-status-manager" port="4713"/>
        <outbound-socket-binding name="mail-smtp">
            <remote-destination host="localhost" port="25"/>
        </outbound-socket-binding>
    </socket-binding-group>
</server>`

As you see Port 9991 is not added.

Also not the admin-port bindung. Only the env-var PROXY_ADDRESS_FORWARDING:
`[jboss@login-netzebw-keyclo-0 ~]$ cat /opt/jboss/keycloak/standalone/configuration/standalone.xml | grep "undertow:7.0" -A 18
        <subsystem xmlns="urn:jboss:domain:undertow:7.0" default-server="default-server" default-virtual-host="default-host" default-servlet-container="default" default-security-domain="other">
            <buffer-cache name="default"/>
            <server name="default-server">
                <http-listener name="default" socket-binding="http" redirect-socket="https" proxy-address-forwarding="${env.PROXY_ADDRESS_FORWARDING:false}" enable-http2="true"/>
                <https-listener name="https" socket-binding="https" proxy-address-forwarding="${env.PROXY_ADDRESS_FORWARDING:false}" security-realm="ApplicationRealm" enable-http2="true"/>
                <host name="default-host" alias="localhost">
                    <location name="/" handler="welcome-content"/>
                    <http-invoker security-realm="ApplicationRealm"/>
                </host>
            </server>
            <servlet-container name="default">
                <jsp-config/>
                <websockets/>
            </servlet-container>
            <handlers>
                <file name="welcome-content" path="${jboss.home.dir}/welcome-content"/>
            </handlers>
        </subsystem>
    </profile>`

For testing purpose I added the hello world shell script of which I dont get a output in the logs as well.
I checked also the standalone-ha.xml which is missing the entrys...

Further configs which may take effect:

`extraPorts: 
      - name: admin-port
        containerPort: 9991
        protocol: TCP
    extraArgs: "-c standalone.xml"
[...]
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9990"
      extraPorts: 
        - name: admin-port
          port: 9991
          protocol: TCP`

My minimum goal is to set the admin-console on a different port. 
Ideally I would like to set the admin-console only accessable by local IP-Address.

At the moment I call https://*myhost*/auth/admin/master/console/#/realms 
... with success what I don't want to be successfull

Do I miss a information to solve this?

What is the suggested approach to protect the admin-console from public access?

KR

**Comment by unguiculus** [comment]
Please provide your configuration and format the issue properly so one can follow. Thanks.

**Comment by oscarlofwenhamn** [comment]
Looks like you're using the `extraArgs` string attribute for your startup commands, when now it's simply the array `args`.

I just made that mistake and it took too long before I double checked the values options and found it has changed `string extraArgs` -> `array args`.
