### ISSUE TITLE
jq is missing in Keycloak

### ISSUE THREAD

**Issue by lukaszlenart** [codecentric/helm-charts#342]
We are using an older Keycloak Chart which contains `jq` commands, after switching to the latest Codecentric Chart the `jq` command is not available. We use `jq` to parse output from `kcadm.sh` tool.

Not sure if I should register this issue here or maybe directly in JBoss JIRA.

**Comment by unguiculus** [comment]
The chart uses the official image. Either provide your own image or request that from the JBoss folks.

**Comment by lukaszlenart** [comment]
Right, wrong repo :)
