### ISSUE TITLE
Sticky Sessions for Ingress

### ISSUE THREAD

**Issue by cjohn001** [codecentric/helm-charts#361]
Hello together,
I am just trying to get keycloak in ha set up with this chart. Got to keycloak instances behind ingress running now. I read in the documentation that for performance reasons one should use sticky sessions for an ingress. It seems like the ingress in this charts does not have annotations in this regards, Can someone give me a hint what I would need to change on the chart? Would be great if the maintainers could extend the README in this respect. 
Apart from that the descriptions are very good. I could set up everything else without issues.

**Comment by unguiculus** [comment]
This is not specific to the Keycloak chart and depends on the ingress controller you use. For ingress-nginx, have a look here: https://kubernetes.github.io/ingress-nginx/examples/affinity/cookie/

**Comment by cjohn001** [comment]
Hello @unguiculus  ,
thanks for your feedback. Indeed I am using nginx as ingress. Could you maybe provide configuration settings for nginx that are known to work with keycloak? Thanks for taking the time.

Best regards,
 Christoph
