### ISSUE TITLE
Infinispan rebalancing during initial bootstrap of Keycloak gives false sense of readiness

### ISSUE THREAD

**Issue by sarlaccpit** [codecentric/helm-charts#363]
**Overview**

I am using the chart with the `keycloak.replicas` count to 3, to enable the HA bits and pieces.   This generally works very well but there is a problem I'm facing with regards to the overall cluster readiness and bootstrapping.

In my environment, I want to closely track how a realm gets created, and what setting gets applied to it, in an iterative fashion rather than using the realm import capability which takes in a whole json representation of the realm at once.

The problem I'm running into is that once the `helm` installation of the Keycloak cluster as a whole completes, everything "appears" ready.    All 3 pods are up and running, the K8 service in front of it is good to go etc.

However, the infinispan cluster can be seen doing some activity still (rebalancing or somehow finishing up its bootstrapping).

I have a script to create the realm (using KCADM for example) and run some realm update command to turn this or that option off in the new realm.

The script looks roughly like:

```
  $KCADM config credentials --server $KEYCLOAK_INTERNAL_SV_URL --realm master --user $KEYCLOAK_USER --password $KEYCLOAK_PASSWORD
   echo -e "Deleting previously half-created realm $REALM if it exists"
  $KCADM delete realms/$REALM
  # echo "Sleeping before next attempt..."
  # sleep $REALM_CREATION_INITIAL_WAIT_S
  # echo "Done sleeping."

  set -e
  echo -e "Creating $REALM realm"
  $KCADM create realms -s realm=$REALM -s enabled=true
  echo -e "Setting display attributes"
  $KCADM update realms/$REALM -s "displayName"="..."
  $KCADM update realms/$REALM -s "displayNameHtml"="..."
  echo -e "Setting SSO timeout values"
  $KCADM update realms/$REALM -s "ssoSessionIdleTimeout"=28800
  $KCADM update realms/$REALM -s "ssoSessionMaxLifespan"=36000
  ...
```

The problem is that since the script does not know what Keycloak is _truly_ ready, I often run into situations where errors are returned to the KCADM client, usually some sporadic random 401s, or "Conflict detected. See logs for details".  (when that happens, some postgresql errors about duplicate keys can be observed)

Because the script doesn't know when it's safe, and can experience these errors in the middle of execution, it runs in a retry loop with some sleep in between, hoping for the best.  It starts by deleting the previous unfinished realm if it exists and tries to create it again.  sleeps... tries again... until eventually the conflicts/inconsistencies have somehow resolved themselves and the realm is created, in perfect working order.

(the cluster eventually does get in a consistent state but it can take some time, and the retries which create/delete the realm actually worsen things which then take longer to stablelize)

**Summary**

So the bottom line is that the liveness/readiness probes in the chart, which are focused on querying the /auth/realms/ endpoints, do not really tell the full story.  And an eager bootstrapping script can run into trouble.

My workaround is of course some sleeps, and retries but that is suboptimal.  

Is there somehow a way to get a more accurate view into whether or not Keycloak HA, as a whole and from inside out, is actually ready?   (I suspect this isn't a chart issue at its core and may require integration changes with Keycloak server itself but I'm not sure).

**Comment by kcirtapj** [comment]
Hi,
This raised my attention.

> I often run into situations where errors are returned to the KCADM client, usually some sporadic random 401s, or "Conflict detected. See logs for details". (when that happens, some postgresql errors about duplicate keys can be observed)

Maybe it is related to this issue:
https://github.com/codecentric/helm-charts/issues/364

So I have 3 replicas and they seem to be running and everything is fine, especially if you deal with user/password-authentification. But if I work with a bearer-token, simplest use-case is to retrieve a token and access the keycloak  admin-api with the admin-cli client, I will randomly hit a 401, because a node does not know a about the valid token provided by a another cluster member.

Do the cluster members really recognize each other?

Which versions of the chart and jboss/keycloak image version are you using?
How did you adapt the chart values.yml file besides the replicas: 3 param?

**Comment by sarlaccpit** [comment]
Hi @kcirtapj  thanks for your reply.      The chart is a private fork of the 8.2.2 version of the chart.  And the Keycloak version is 10.0.2.

Other than setting a particular password for the admin user, and some customization like passing in some cli commands like:

```
/subsystem=keycloak-server/spi=truststore/:add
/subsystem=keycloak-server/spi=truststore/provider=file/:add(enabled=true)
/subsystem=keycloak-server/spi=truststore/provider=file/:map-put(name=properties,key=file,value=/opt/jboss/keycloak/standalone/configuration/keystores/truststore.jks)
/subsystem=keycloak-server/spi=truststore/provider=file/:map-put(name=properties,key=password,value=${env.TRUSTSTORE_PASSWORD})
/subsystem=keycloak-server/spi=truststore/provider=file/:map-put(name=properties,key=hostname-verification-policy,value=WILDCARD)
/subsystem=keycloak-server/spi=truststore/provider=file/:map-put(name=properties,key=disabled,value=false)
```

and

```
/subsystem=keycloak-server/spi=hostname/provider=fixed/:map-put(name=properties,key=alwaysHttps, value=true)
```

that's pretty much it.   Oh, and the most important thing which is not in the original chart is  :  

```
apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-realm-creation
  labels:
    {{- include "keycloak.commonLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
spec:
  backoffLimit: 10
  template:
    spec:
      containers:
      - name: keycloak-create-realm
        image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["/opt/jboss/keycloak/tools/bootstrap.sh"]
        env:
          - name: NAMESPACE
            value: {{ .Release.Namespace }}
      ...
```

Where that bootstrap.sh script is a custom script that basically does what is shown in the issue description: attempts to create the realm.


What I feel is this:

Like I had described, the first couple failures of this script are 401s, which is absolutely in line with what you explained with the tokens.  In other words, I think the members don't know each other _yet_.     However, that eventually fixes itself and the cluster is definitely HA eventually.     

So I don't think we're running into a straight instance of the #364 issue.   I think we're getting past that transient state fairly quickly and then going into the more problematic "conflicts detected" state.   Which again, eventually resolves itself.   But it takes some time and some black magic sleeps to get there.

**Comment by sarlaccpit** [comment]
@kcirtapj do you have any input after my last post?  Thank you.
