### ISSUE TITLE
Keycloak :  Enable features in keycloak through helm deployment

### ISSUE THREAD

**Issue by surya17** [codecentric/helm-charts#37]
Hi Team,

With keycloak deployment some of the features are disabled by default. But then is there a way to enable features through helm deployment?
I want to enable "Script authenticator" which allows to add "custom js" scripts  which is disabled by default. This can be enabled using like option Dkeycloak.profile.feature.script=enabled as per keycloak doc. So want to know how we can pass this option on deploying the keycloak through helm

**Comment by unguiculus** [comment]
Please check the readme. The chart allows you to set extra arguments like so:

```yaml
keycloak:
  extraArgs: "-Dkeycloak.profile.feature.script=enabled"
```

**Comment by starman2015** [comment]
I added extraArgs to values.yaml

But when I receive a request, I get a response:
{"error":"Feature not enabled"}

```
keycloak:
  extraArgs:
    [
      "-Dkeycloak.profile.feature.token_exchange=enabled",
      "-Dkeycloak.profile.feature.admin_fine_grained_authz=enabled"
    ]
```

**Comment by nloke** [comment]
@starman2015  from the documentation (https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/README.md#jvm-settings) is below not the following format?

`extraEnv: |
  - name: JAVA_OPTS
    value: >-
      -XX:+UseContainerSupport
      -XX:MaxRAMPercentage=50.0
      -Djava.net.preferIPv4Stack=true
      -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS
      -Djava.awt.headless=true`
