### ISSUE TITLE
Keycloak X

### ISSUE THREAD

**Issue by oliverkane** [codecentric/helm-charts#375]
Are there any plans to support the cloud-native Keycloak.X distribution?  I've been playing with this a bit locally and it's much lighter-weight, and lightning fast.

https://www.keycloak.org/2020/12/first-keycloak-x-release.adoc

**Comment by unguiculus** [comment]
The Keycloak chart will never support Keycloak.X which is a totally different product. It will require a chart of its own. There are currently no plans yet for this. Also, it is still in a preview state and lacks proper documentation.

**Comment by oliverkane** [comment]
Thanks for letting me know. Sounds like a fun hobby project to work on.
