### ISSUE TITLE
Keycloak 12 

### ISSUE THREAD

**Issue by predragpjanovic** [codecentric/helm-charts#377]
When we could expect support for Keycloak 12?

**Comment by zmingxie** [comment]
I'm able to use the current chart to deploy Keycloak 12. All you need to do is setting the `image.tag` version string to `12.0.2`

**Comment by thomasdarimont** [comment]
FYI Keycloak 12 (up to 12.0.2) currently contains a few bugs that might cause trouble in production.

For now I'd recommend to stay on 11.0.3 until 12.0.3 is released with fixes.

The Keycloak team is currently working a fixed 12.0.3 release.
See: https://groups.google.com/g/keycloak-dev/c/yxjxV-nsKkA

More problems with 12.0.0-2 can be found here: https://groups.google.com/g/keycloak-dev

**Comment by christianbreyer** [comment]
12.0.3 has been released some days ago. Could you confirm that his version is ready for production and the issue you mentioned has been fixed?

**Comment by thomasdarimont** [comment]
12.0.3 still has an issue with writeable LDAP federation: https://groups.google.com/g/keycloak-dev/c/KUffDUWSu88/m/B9M7rGEMAQAJ

**Comment by thomasdarimont** [comment]
Keycloak 12.0.4 was just released on monday and seems to fix the mentioned issues.
