### ISSUE TITLE
[Keycloak] Guidance for selecting chart version

### ISSUE THREAD

**Issue by Xendar** [codecentric/helm-charts#392]
Hello!

We use Keycloak for a project, and some colleagues started to duplicating the chart repository, and created several custom `values.yaml` files, which makes it hard to maintain.
In order to simplify the maintenance and remove the mix-up, I was planning on removing the duplicated chart and version, only version the custom values and install the chart from codecentric directly.

Checking the documentation I see in the examples that the chart version can be defined at installation time with `--version=9.0.0`. However, checking the repo history, I see that the latest available version is `9.9.2`.
Is the documentation simply not up to date and I should select `9.9.2`? Or should I stick to `9.0.0` for some reason?

Thanks for your help to a Helm newbie!

**Comment by unguiculus** [comment]
I'm not sure I understand what you mean. Why would you exactly prefer 9.0.0 over 9.9.2? Where do you think documentation is not up to date?

**Comment by Xendar** [comment]
> I'm not sure I understand what you mean. Why would you exactly prefer 9.0.0 over 9.9.2? Where do you think documentation is not up to date?

It appears at some point in the readme of Keycloak, which was somehow confusing 😅
![Screenshot_20210219-193732.jpg](https://user-images.githubusercontent.com/24693144/108546878-08c56500-72ea-11eb-9d51-187d5d0b33a3.jpg)

**Comment by unguiculus** [comment]
That's just an example of how to install a specific version.
