### ISSUE TITLE
Wrong ingress path type

### ISSUE THREAD

**Issue by unbreakabl3** [codecentric/helm-charts#403]
Hello, dear all. 

Found today a strange behaviour. When I run helm with --set=ingress.rules[0].paths=[/], im getting an error: 

"Error: values don't meet the specifications of the schema(s) in the following chart(s):
keycloak: ingress.rules.0.paths: Invalid type. **Expected: array, given: string**"

So, looks like for him [] is not array.

If I run '--set=ingress.rules[0].paths=**{/}**' - it is working!

So, {} is an array.

In the [documentation](https://artifacthub.io/packages/helm/codecentric/keycloak) I can found the following: 

ingress.rules[0].paths | Paths for the Ingress rule | [/]
-- | -- | --

Helm version: version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}

Chart version: keycloak-9.9.3

App version: 11.0.3

Kubernetes: 1.19.7

Thank you.

**Comment by neogeogre** [comment]
because it's now in the values:
```yaml
  paths:
    - path: /
      pathType: Prefix
```
instead of:
```yaml
  paths:
    - /
```
