### ISSUE TITLE
Looks like the codecentric/keycloak page on artifacthub.io doesn't work

### ISSUE THREAD

**Issue by RothAndrew** [codecentric/helm-charts#418]
This could totally be the wrong place for this. If so, feel free to close this.

Looks like the page for the codecentric/keycloak chart on [ArtifactHub](https://artifacthub.io/packages/helm/codecentric/keycloak) (previously known as HelmHub at https://hub.helm.sh) isn't working.

At first I thought it might be an issue with ArtifactHub, but every other chart page I have looked at has worked fine.

Just want to make sure it is on your radar

Screenshots:
![image](https://user-images.githubusercontent.com/16000938/115574563-bd9ae480-a28f-11eb-9e44-4f5a10c724d3.png)

**Comment by tegioz** [comment]
Hi @RothAndrew 👋 

Thanks for reporting this! We've just fixed it in https://github.com/artifacthub/hub/pull/1262, we'll deploy it soon 🙂

**Comment by RothAndrew** [comment]
Thanks!
