### ISSUE TITLE
Because of read only file system, I cannot save emails on disk

### ISSUE THREAD

**Issue by rohitkalsarpe** [codecentric/helm-charts#419]
My config file

` 
serviceAccount:
  create: false

service:
  port:
    smtp: 587

ingress:
  enabled: true
  hosts:
    - host: something.com
      paths: ["/"]

extraEnv:
  - name: MH_STORAGE
    value:  "maildir"
  - name: MH_MAILDIR_PATH
    value: "/home/mailhog/" 

`

I create mailhog with
`helm install mailhog codecentric/mailhog -f configfile `

Because of read only file system, I cannot save emails on disk

**Comment by mircohaug** [comment]
You can try to mount a volume at the folder you want to save your mail at.

**Comment by romikoops** [comment]
The chart does not support mounting a volume currently. Another issue, your cloud provider should support `ReadWriteMany`
