### ISSUE TITLE
enableServiceLinks only available in kubernetes >= 1.13

### ISSUE THREAD

**Issue by dojadop** [codecentric/helm-charts#42]
UPGRADE FAILED
Error: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec): unknown field "enableServiceLinks" in io.k8s.api.core.v1.PodSpec
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec): unknown field "enableServiceLinks" in io.k8s.api.core.v1.PodSpec

Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

Related to https://github.com/codecentric/helm-charts/pull/19

**Comment by pixie79** [comment]
Bump - i am seeing this issue to with EKS, can we get the patch merged please
