### ISSUE TITLE
How to use PostgreSQL HA with this in same master chart?

### ISSUE THREAD

**Issue by joeb123456** [codecentric/helm-charts#424]
How to use PostgreSQL HA with this in same master chart?

**Comment by mircohaug** [comment]
I would not recommend this. When your setup is sophisticated enough to require a HA Database you should host your database in a dedicated helm chart. 

However if you really want to do this, all values under the `postgresql` get pushed to the postgresql subchart so you would have to look up which configuration values the subchart in the used version accepts and pass them under the `postgresql` key to this chart. But again I do not recommend or support this.
