### ISSUE TITLE
[Question] Does this chart support multi region deployment?

### ISSUE THREAD

**Issue by rajeshneo** [codecentric/helm-charts#426]
I brought up a single region multi-instance keycloak cluster backed up with RDS database using this chart. just wondering is there support for multi-region cluster as well? 
https://www.keycloak.org/2018/01/keycloak-cross-data-center-setup-in-aws.html

**Comment by mircohaug** [comment]
Hi @rajeshneo if your underlying K8s spans multiple regions you could define a node selector to achieve this. But this K8s setup comes with a bunch of complexity.

But you could instead have a dedicated k8s and keycloak in two regions and connect them on the application layer. Have a look at https://www.keycloak.org/docs/latest/server_installation/#crossdc-mode for a more up to date documentation.
