### ISSUE TITLE
[Keycloak] Switch docker.io to quay.io for Keycloak images

### ISSUE THREAD

**Issue by thomasdarimont** [codecentric/helm-charts#429]
Quay.io is the docker registry provided by Redhat.

- The Keycloak images are first released to quay.io 
- Most redhat examples use quay.io as their repository
- quay.io does not have strict usage quotas as docker.io

The Keycloak image is quay.io/keycloak/keycloak

**Comment by preston** [comment]
Hi @thomasdarimont - We're wanting to go from the Keycloak 16.1.1 Docker Hub image to v17 from quay.io. Should this be as easy as updating the registry and image name? Or are there any configuration differences in the quay.io images going forward?

**Comment by thomasdarimont** [comment]
For the keycloak chart you can use the `quay.io/keycloak/keycloak` but make sure to use the tag `17.0.1-legacy` for the Wildfly based version, since just `17.0.1` would give you the new quarkus based version.

Note that the new helm-chart for keycloax will be released very soon: https://github.com/codecentric/helm-charts/pull/533

**Comment by preston** [comment]
Thanks @thomasdarimont ! The 17.0.1-legacy tag seems to be working for me. Is the quarkus-based 17.0.1 tag compatible with the *-legacy wildfly builds? Any migration guidance, especially on anything we need to change to follow the recommended migration path on simple non-k8s Docker community deployments such as mine, very much appreciated!

**Comment by thomasdarimont** [comment]
@preston take a look at: https://www.keycloak.org/migration/migrating-to-quarkus
