### ISSUE TITLE
metrics scraping on port 9990 and /metrics context path not working

### ISSUE THREAD

**Issue by bmmadhuprasad** [codecentric/helm-charts#436]
HI Team,

I have enabled service monitor to allow Prometheus to scrape metrics but prometheus not able to scrape metrics on port 9990 and path /metrics 
![image](https://user-images.githubusercontent.com/77019526/121382766-8c23c880-c964-11eb-9b72-95912247c5c4.png)

when i checked inside keycloak Pod port 9990 is not listening

sh-4.4$ curl http://10.0.3.226:9990/metrics
curl: (7) Failed to connect to 10.0.3.226 port 9990: Connection refused
sh-4.4$ curl http://10.0.3.226:9990
curl: (7) Failed to connect to 10.0.3.226 port 9990: Connection refused
sh-4.4$
![image](https://user-images.githubusercontent.com/77019526/121382848-a067c580-c964-11eb-80ac-771598bca2c6.png)

But other ports 8080 8443 are listening only 9990 is not working
Need suggestion to fix this issue please let me know if i am missed something.

![image](https://user-images.githubusercontent.com/77019526/121383173-defd8000-c964-11eb-9b2e-387e59e6ed0f.png)

**Comment by mircohaug** [comment]
You need to enable metrics as well. Have a look at [the docs](https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#prometheus-metrics-support)
