### ISSUE TITLE
Dead link PostgreSQL in Keycloak Chart readme

### ISSUE THREAD

**Issue by adrianmatei-me** [codecentric/helm-charts#44]
The chart has an optional dependency on the [PostgreSQL](**https://github.com/kubernetes/charts/tree/master/codecentric/postgresq**l) chart.
By default, the PostgreSQL chart requires PV support on underlying infrastructure (may be disabled).

**Comment by unguiculus** [comment]
I'm not sure I understand what this issue is about, neither did I find a dead link in the readme.

**Comment by adrianmatei-me** [comment]
Sorry I thought I pasted the link
"The chart has an optional dependency on the PostgreSQL  **https://github.com/kubernetes/charts/tree/master/codecentric/postgresql)** "
