### ISSUE TITLE
[keycloak] Bump postgresql chart dependency

### ISSUE THREAD

**Issue by mascah** [codecentric/helm-charts#45]
This has been raised a few times in the past regarding this chart using an _extremely_ old version of the stable/postgres chart (0.15.0). The postgres chart is on 5.1.2 today and has significant improvements. 

It looks like the keycloak chart is also about to have a major version bump, which would be a great opportunity to also include this change.

**Comment by unguiculus** [comment]
This should be part of the major chart upgrade. The problem is that the Postgres chart had breaking changes. Feel free to create a PR to speed things up.
