### ISSUE TITLE
nc: bad address 'keycloak-postgresql-primary' when postgres replication is enabled

### ISSUE THREAD

**Issue by davide-talesco** [codecentric/helm-charts#456]
Hi guys,

first of all thanks for the chart!
I am not too sure I am doing anything wrong or is it a bug with the chart.

When postgres replication is enabled keycloak cannot start due to pgchecker unable to connect to postgres.

values.yaml
```yaml
postgresql:
  replication:
    enabled: true
```

kubectl logs keycloak-0 -c pgchecker
`
nc: bad address 'keycloak-postgresql-primary'
nc: bad address 'keycloak-postgresql-primary'
nc: bad address 'keycloak-postgresql-primary'
nc: bad address 'keycloak-postgresql-primary'
...
nc: bad address 'keycloak-postgresql-primary'
nc: bad address 'keycloak-postgresql-primary'
nc: bad address 'keycloak-postgresql-primary'
`

Regards,
Davide

**Comment by davide-talesco** [comment]
I noticed you guys use postgresql.primary.fullname to build postgres service name, but looks like you should use common.names.fullname

https://github.com/codecentric/helm-charts/blob/a82e2983db83b73682b9417eb948c9f2b44e0e70/charts/keycloak/templates/_helpers.tpl#L68

**Comment by alex-egorov** [comment]
Same issue. Keycloak helm chart does not work with bitnami/postgresql with replication enabled
