### ISSUE TITLE
How to configure liveness/readinessProbe url's for specific realms ?

### ISSUE THREAD

**Issue by rvanderboom** [codecentric/helm-charts#46]
Hey,

how can i configure the livenessProbe/readynessProbe for a specfic Realm for keycloak ?
We have a keycloak setup with different whitelabel reamls, and therefore the liveness/readiness should be on realms/<whitelabel-realm name>.

What it looks like is that only the keycloak basepath is configurable:
 {{ if ne .Values.keycloak.basepath "" }}/{{ .Values.keycloak.basepath }}{{ end }} 
 {{ if ne .Values.keycloak.basepath "" }}/{{ .Values.keycloak.basepath }}{{ end }} /realms/master

But we want https://account-dev.fd.nl/auth/realms/FD

this because when we run a loadtest and we restart 1 of the 2 nodes, it detects to early the node is up and we get 500 errors for a short time.  This becaus the custom FD realm (with custom provider features), is not up yet, its up after keycloak and master realms are up.

Is there another way to configure this  ?

Thanks in advanced.

**Comment by unguiculus** [comment]
There is currently no way to configure this. Feel free to submit a PR.

**Comment by unguiculus** [comment]
Fixed in rel. 6.0.0
