### ISSUE TITLE
Keycloak not working with traefik forwardauth middleware

### ISSUE THREAD

**Issue by MarjanJordanovski** [codecentric/helm-charts#461]
I deployed traefik and keycloak on kubernetes. I created a client on keycloak and I want keycloak to protect access to my application. I created ingressroute for traefik, where my application is exposed, and that ingressroute is using middleware which is doing forwardauth to keycloak address (let's name it address1):
https://mykeycloakURL/auth/realms/RELMNAME/protocol/openid-connect/auth?scope=openid&response_type=code&client_id=CLIENTID&redirect_uri=https://myprotectedapplicationURL/&prompt=consent
When I just enter this address1 to browser, proper login screen appears. But when I access my https://myprotectedapplicationURL , traefik does forwardauth toaddress1, but since login page returns status code 200 when loaded, traefik automatically navigates to https://myprotectedapplicationURL without waiting for successful authentication. How to fix this?

**Comment by justmike1** [comment]
hey, I have the same issue using keycloakx (migrating from keycloak), have you found a fix?

**Comment by MarjanJordanovski** [comment]
Hey @justmike1 , was a long time ago, but as I remember I was able to fix it with the keycloak-gatekeeper, behind which was my protected application. So as I remember, keycloack would communicate with the gatekeeper, and gatekeeper will let the request go through to the application if authenticated. I believe I used this helm chart for gatekeeper deployment:
https://artifacthub.io/packages/helm/gabibbo97/keycloak-gatekeeper
