### ISSUE TITLE
image release versions for ExtraInitContainers (i.e. custom themes) through Values/variables

### ISSUE THREAD

**Issue by rvanderboom** [codecentric/helm-charts#47]
Hey,

it is already possible to add extraInitContainers for themes that are maintained/build separately.  
What we like is that we can dynamicaly  determine the release-number of this themes container:  

extraInitContainers: |
    - name: themes
      image: docker-repo.xxx.org/theme:{{ .Values.themes-version }}
   - name:  authenticator-provider
      image: docker-repo.xxx.org/authenticator-provider: {{ .Values.authenticator-version }}

The version release number we use is actually the commit-id-hash and we want to pass it with ci gitlab.   
The problem now is you only can make extraInitContainers configurable as a whole since you can not use Values in a values.yaml file.       
Is it possible to make extraInitcontaiers more flexibale, for example to not define extraInitContainsers as a value itself but more like the above, defining name, image test as values array?

Or is there another solution you can suggest how is the preffered way ?

**Comment by unguiculus** [comment]
This is already possible. The `tpl` function is used to process the value for `extraInitContainers`. That's the reason why it has to be a string. You can use templating exactly as you described above. Just set the values you specified, either in a values file or via CLI: `--set themes-version=42`

**Comment by rvanderboom** [comment]
mmm strange because everywhere i read its not supported to have values into values files itself, it also gives error about not understanding value within values files.
we have to invest further then

**Comment by unguiculus** [comment]
By defauolt, it's indeed not supported. However, the `tpl` function does the trick. Look at this example in the readme:
https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#using-google-cloud-sql-proxy

**Comment by unguiculus** [comment]
Closing this. Feel free to reopen if this is still an issue for you.
