### ISSUE TITLE
What's right way to upgrade keycloak to new version

### ISSUE THREAD

**Issue by angeloudy** [codecentric/helm-charts#482]
There are quite a few steps for upgrading keycloak to newer version as documented in the official [documentation](https://www.keycloak.org/docs/5.0/upgrading/).
What's the right way to upgrade keycloak to new version in helm chart?
Do I just change the keycloak image version? I tried this and didn't work because our custom themes are not compatible with the new version.

My other question is which helm chart version should I use for certain keycloak version? Is there a mapping. I know that helm chart and docker image are maintained separately, but I would like to know which helm chart version is best for a specific keycloak version.

Thanks

**Comment by griftir** [comment]
Having same problem. It just keeps installing 12.0.4 even if I do a clean install
