### ISSUE TITLE
Add support for networking.k8s.io/v1/Ingress resource in mailhog chart

### ISSUE THREAD

**Issue by jwandrews** [codecentric/helm-charts#483]
The `mailhog` helm chart does not yet support k8s v1.22+ cluster due to the missing `networking.k8s.io/v1/Ingress` template support. It seems `keycloak` has it, so the logic could just be copied over.

I am more than happy to provide a PR if need be

**Comment by jwandrews** [comment]
oh, it seems there's already a PR for this: #474 
although it seems that it is not BC with older cluster versions

**Comment by jwandrews** [comment]
Added PR to make `mailhog` chart consistent with `keycloak` chart in terms of Ingress template: 
- https://github.com/codecentric/helm-charts/pull/484

**Comment by mircohaug** [comment]
closed with https://github.com/codecentric/helm-charts/pull/455
