### ISSUE TITLE
Ingress v1 : capabilities are not evaluated correctly

### ISSUE THREAD

**Issue by olevitt** [codecentric/helm-charts#496]
Hi,

as discussed in this commit : https://github.com/codecentric/helm-charts/commit/cb624cf356851ef3fe2cd0fba0762b1d485e44ff  
the check that is used on both mailhog and keycloak charts to figure out which ingress version to use (Kubernetes `1.22` which released like two months ago removed the old ingresses apiVersion so many users are now upgrading and need to have the new ingress class).  
From my testing, the current check `{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}` (see https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/templates/_helpers.tpl#L82) does not work when using `helm template` (or using workflows that rely on helm template such as `argoCD`.  
We could use the same type of check as in other charts (it seems most of the charts maintainers are in the process of migrating their ingress apiVersion check). For example https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/_helpers.tpl#L135
or
https://github.com/hashicorp/vault-helm/blob/main/templates/server-ingress.yaml#L13  

Any idea on the best check to implement ?

**Comment by SeWieland** [comment]
Hmmm.. I do have the same issue, however in other charts the capability check works flawlessly!
I don't think a "manual value setting" is the resolution here...

E.g. the ingress of this chart works for me just fine: https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/templates/ingress.yaml

=> They have defined their capability check in the actual ingress.yaml and not in the helper.
But I have absoultely no cue why it won't work using the helper..

**Comment by juliohm1978** [comment]
@SeWieland 
What Kubernetes version are you using? Up until 1.21, `networking.k8s.io/v1beta1` is still available, so the chart works when it sends the Ingress to that API.

On a side note: When you query the apiserver, it might be showing `networking.k8s.io/v1`, but that does not represent the actual api used to create the object. The apiserver prints an apiVersion it considers appropriate, but the object might've been added through an older endpoint (https://github.com/kubernetes/kubernetes/issues/58131).

**Comment by SeWieland** [comment]
@juliohm1978 I'm on 1.21 and the chart still works. However the helm liniter produces the warning that the API will be deprecated in 1.22+. As this is the only warning I get in a lot of charts, I think this should be changed.


I already created a PR, however for both charts. As this is not accepted, I'll change that
