### ISSUE TITLE
What is the suggested upgrade strategy for keycloak?

### ISSUE THREAD

**Issue by alkallio** [codecentric/helm-charts#50]
Hi! I'm opening this issue because I couldn't find anything specific in the docs.  
Is there any suggested upgrade strategy when releasing a new keycloak version or theme updates?

According to Keycloak's [upgrading guide](https://www.keycloak.org/docs/5.0/upgrading/index.html) there is data in certain [directories](https://www.keycloak.org/docs/5.0/upgrading/index.html#_install_new_version) that needs to be retained. Something else I noticed, is that every time I upgrade keycloak, all users sessions are deleted, despite having verified that the infinispan cluster is working properly.

What I'm trying now as a solution, is to properly set up poddisruptionbudget but I was wondering if you already follow any specific strategy during updates to avoid issues like deleting all active user sessions or I'm missing something very obvious that results in this issue.

Thanks for all your work!

**Comment by chensunny** [comment]
Although the poddisruptionbudget is set, if the data is not synchronized during the rolling update, the user session will still be lost. I think the better way is to solve this problem through the remote cache (like redis), but we extend the keycloak Session  Provdier found that the workload was quite a lot and it didn't feel good to expand.

https://lists.jboss.org/pipermail/keycloak-dev/2018-May/010787.html
https://infinispan.org/docs/stable/user_guide/user_guide.html#distribution_mode

**Comment by unguiculus** [comment]
This is an issue with Keycloak itself when Infinispan caches cannot by synchronized across major or sometimes even minor upgrade.

**Comment by unguiculus** [comment]
Closed this for now. Feel free to reopen if you still have questions.
