### ISSUE TITLE
How to add another admin user / reset current admin password on already running Keycloak instance

### ISSUE THREAD

**Issue by ferdinandosimonetti** [codecentric/helm-charts#508]
Hello,
I've lost my admin password, it isn't the one referenced in Secret nor the one referenced inside Helm values.yaml.
A colleague suggested 

`bash-4.4$ cd /opt/jboss/keycloak/
bash-4.4$ ./bin/add-user-keycloak.sh -u admin -p adm1n -r master
Picked up JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport -XX:MaxRAMPercentage=10.0
Added 'admin' to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json', restart server to load user`

But... how can I restart the server without killing the pod?
Thanks in advance

**Comment by mircohaug** [comment]
I think you have to kill the pod for a restart.
