### ISSUE TITLE
[Keycloack] 502 Bad Gateway - Proxy Buffer Size

### ISSUE THREAD

**Issue by c00** [codecentric/helm-charts#509]
A common error that happens with Keycloak on K8s is the 502 Bad Gateway error. \this has to do with the Proxy Buffer size of the Ingress. For example, [here's a solution](https://stackoverflow.com/a/68811151/1686932).

Since this is such a common occurence and the readme of this chart is super helpful in a variety of other ways, I want to suggest adding a note to the Readme to address this issue.

**Comment by nyogendran** [comment]
I pretty much tried out all the options to fix the 502 Bad Gateway issue. But I could not.
Referred [Keycloak X](https://github.com/codecentric/helm-charts/blob/master/charts/keycloakx/values.yaml) to install Keycloak using Helm.

helm version
version.BuildInfo{Version:"v3.17.2", GitCommit:"cc0bbbd6d6276b83880042c1ecb34087e84d41eb", GitTreeState:"clean", GoVersion:"go1.24.1"}

% helm search repo codecentric/keycloak
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                                       
codecentric/keycloak    18.10.0         17.0.1-legacy   Open Source Identity and Access Management For ...
codecentric/keycloakx   7.0.1           26.0.7          Keycloak.X - Open Source Identity and Access Ma...

% kubectl version  
Client Version: v1.32.2
Kustomize Version: v5.5.0
Server Version: v1.32.0

values-x.yaml
`fullnameOverride: ""

nameOverride: ""

replicas: 1

image:
  repository: "quay.io/keycloak/keycloak"
  tag: "26.0.7"
  pullPolicy: IfNotPresent

enableServiceLinks: true

updateStrategy: RollingUpdate

podManagementPolicy: Parallel

restartPolicy: Always

service:
  annotations: {}
  labels: {}
  type: LoadBalancer
  loadBalancerIP: ""
  httpPort: 8080
  httpNodePort: null
  httpsPort: 8443
  httpsNodePort: null
  extraPorts: []
  externalTrafficPolicy: "Cluster"
  sessionAffinity: ""
  sessionAffinityConfig: {}

serviceHeadless:
  enabled: true
  annotations: {}

skipInitContainers: false

terminationGracePeriodSeconds: 30

clusterDomain: cluster.local

command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--hostname-strict=false"

extraEnv: |
  - name: KC_BOOTSTRAP_ADMIN_USERNAME
    value: admin
  - name: KC_BOOTSTRAP_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-admin-creds
        key: password
  - name: JAVA_OPTS_APPEND
    value: >-
      -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless

dbchecker:
  enabled: true
  image:
    repository: docker.io/busybox
    tag: 1.32
    pullPolicy: IfNotPresent
  securityContext:
    allowPrivilegeEscalation: false
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
  resources:
    requests:
      cpu: "20m"
      memory: "32Mi"
    limits:
      cpu: "20m"
      memory: "32Mi"

database:
  vendor: postgres
  hostname: kspg-postgresql.ns-sample.svc.cluster.local
  port: 5432
  database: keycloak_db
  username: keycloak_user
  existingSecret: keycloak-db-creds
  
ingress:
  enabled: true
  ingressClassName: "nginx"
  servicePort: http
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    nginx.ingress.kubernetes.io/proxy-buffers: "4"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  labels: {}
  rules:
    -
      host: 'keycloak.mydomain.local'
      paths:
        - path: '/'
          pathType: Prefix
  tls:
    - hosts:
        - keycloak.mydomain.local
      secretName: keycloak-server-certs

proxy:
  enabled: true
  mode: forwarded
  http:
    enabled: true

metrics:
  enabled: true

health:
  enabled: true

http:
  relativePath: "/auth"
  internalPort: http-internal
  internalScheme: HTTP
  
networkPolicy:
  enabled: false

route:
  enabled: false`

% helm --namespace ns-sample install keycloak codecentric/keycloakx --values ./values-x.yaml
NAME: keycloak
LAST DEPLOYED: Tue Apr  1 20:59:38 2025
NAMESPACE: ns-sample
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
***********************************************************************
*                                                                     *
*                Keycloak.X Helm Chart by codecentric AG              *
*                                                                     *
***********************************************************************

Keycloak was installed with an Ingress and an be reached at the following URL(s):

  - https://keycloak.mydomain.local/

Logs:

% kubectl --namespace ns-sample logs keycloak-keycloakx-0 --follow                        
Defaulted container "keycloak" out of: keycloak, dbchecker (init)
Appending additional Java properties to JAVA_OPTS
Changes detected in configuration. Updating the server image.
Updating the configuration and installing your custom providers, if any. Please wait.
2025-04-01 15:30:04,457 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 18202ms
Server configuration updated and persisted. Run the following command to review the configuration:

        kc.sh show-config

Next time you run the server, just run:

        kc.sh start --hostname-strict=false --optimized

2025-04-01 15:30:19,606 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Starting Infinispan embedded cache manager
2025-04-01 15:30:22,102 INFO  [org.infinispan.CONTAINER] (ForkJoinPool.commonPool-worker-1) ISPN000556: Starting user marshaller 'org.infinispan.commons.marshall.ImmutableProtoStreamMarshaller'
2025-04-01 15:30:23,003 WARN  [org.jgroups.stack.Configurator] (ForkJoinPool.commonPool-worker-1) JGRP000014: ThreadPool.thread_dumps_threshold has been deprecated: ignored
2025-04-01 15:30:23,086 INFO  [org.infinispan.CLUSTER] (ForkJoinPool.commonPool-worker-1) ISPN000078: Starting JGroups channel `ISPN` with stack `kubernetes`
2025-04-01 15:30:23,090 INFO  [org.jgroups.JChannel] (ForkJoinPool.commonPool-worker-1) local_addr: 9c96effe-7ba8-4539-b814-7fd016efff1d, name: keycloak-keycloakx-0-19763
2025-04-01 15:30:23,116 INFO  [org.jgroups.protocols.FD_SOCK2] (ForkJoinPool.commonPool-worker-1) server listening on *.57800
2025-04-01 15:30:25,131 INFO  [org.jgroups.protocols.pbcast.GMS] (ForkJoinPool.commonPool-worker-1) keycloak-keycloakx-0-19763: no members discovered after 2006 ms: creating cluster as coordinator
2025-04-01 15:30:25,166 INFO  [org.infinispan.CLUSTER] (ForkJoinPool.commonPool-worker-1) ISPN000094: Received new cluster view for channel ISPN: [keycloak-keycloakx-0-19763|0] (1) [keycloak-keycloakx-0-19763]
2025-04-01 15:30:25,283 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2025-04-01 15:30:25,537 INFO  [org.infinispan.CLUSTER] (ForkJoinPool.commonPool-worker-1) ISPN000079: Channel `ISPN` local address is `keycloak-keycloakx-0-19763`, physical addresses are `[10.244.1.28:7800]`
2025-04-01 15:30:27,465 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: keycloak-keycloakx-0-19763, Site name: null
2025-04-01 15:30:31,232 WARN  [io.agroal.pool] (main) Datasource '<default>': JDBC resources leaked: 3 ResultSet(s) and 0 Statement(s)
2025-04-01 15:30:31,841 INFO  [io.quarkus] (main) Keycloak 26.0.7 on JVM (powered by Quarkus 3.15.1) started in 26.767s. Listening on: http://0.0.0.0:8080. Management interface listening on http://0.0.0.0:9000.
2025-04-01 15:30:31,843 INFO  [io.quarkus] (main) Profile prod activated. 
2025-04-01 15:30:31,843 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-postgresql, keycloak, micrometer, narayana-jta, opentelemetry, reactive-routes, rest, rest-jackson, smallrye-context-propagation, smallrye-health, vertx]


Issue #1:
when I hit the https://keycloak.mydomain.local, I get "502 Bad Gateway" response.

However, with port-forward (ing), I can access the admin console.

% kubectl --namespace ns-sample port-forward pod/keycloak-keycloakx-0 8080
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
Handling connection for 8080
Handling connection for 8080


http://localhost:8080/auth/realms/master/protocol/openid-connect/auth?client_id=security-admin-console&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fauth%2Fadmin%2Fmaster%2Fconsole%2F&state=006d152a-d950-4fe2-ac90-a73f954b8678&response_mode=query&response_type=code&scope=openid&nonce=418de234-d1fd-461e-90b7-12c42905dc45&code_challenge=LR5Q5ztHedWz-6lVclhed6DP9ECQ5FSPuGgnMqVy2po&code_challenge_method=S256

Issue #2: 
Startup Probe is failing.

% kubectl --namespace ns-sample get pods
NAME                                                        READY   STATUS    RESTARTS          AGE
keycloak-keycloakx-0                                        1/1     Running   0                 12m
kspg-postgresql-0                                           1/1     Running   2 (8h ago)        11d

% kubectl --namespace ns-sample describe pods keycloak-keycloakx-0
Name:             keycloak-keycloakx-0
Namespace:        ns-sample
Priority:         0
Service Account:  keycloak-keycloakx
Node:             minikube/192.168.64.21
Start Time:       Tue, 01 Apr 2025 20:59:39 +0530
Labels:           app.kubernetes.io/instance=keycloak
                  app.kubernetes.io/name=keycloakx
                  apps.kubernetes.io/pod-index=0
                  controller-revision-hash=keycloak-keycloakx-68d5ccb4bd
                  statefulset.kubernetes.io/pod-name=keycloak-keycloakx-0
Annotations:      checksum/config-startup: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
                  checksum/secrets: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
Status:           Running
IP:               10.244.1.28
IPs:
  IP:           10.244.1.28
Controlled By:  StatefulSet/keycloak-keycloakx
Init Containers:
  dbchecker:
    Container ID:  docker://b9bcfacc906b4710dcd86bb63c059a7bcad38dcf39101d4ce3b5d971bbe831c3
    Image:         docker.io/busybox:1.32
    Image ID:      docker-pullable://busybox@sha256:ae39a6f5c07297d7ab64dbd4f82c77c874cc6a94cea29fdec309d0992574b4f7
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      echo 'Waiting for Database to become ready...'
      
      until printf "." && nc -z -w 2 kspg-postgresql.ns-sample.svc.cluster.local 5432; do
          sleep 2;
      done;
      
      echo 'Database OK ✓'
      
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 01 Apr 2025 20:59:40 +0530
      Finished:     Tue, 01 Apr 2025 20:59:41 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     20m
      memory:  32Mi
    Requests:
      cpu:        20m
      memory:     32Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9vp7t (ro)
Containers:
  keycloak:
    Container ID:  docker://51847f0ddbe79c7517d20dfa1a2113d20aa47f4f993d5011de3534a474167f06
    Image:         quay.io/keycloak/keycloak:26.0.7
    Image ID:      docker-pullable://quay.io/keycloak/keycloak@sha256:4388e2379b7e870a447adbe7b80bd61f5fbf04e925832b19669fda4957f05a81
    Ports:         8080/TCP, 9000/TCP, 8443/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Command:
      /opt/keycloak/bin/kc.sh
      start
      --hostname-strict=false
    State:          Running
      Started:      Tue, 01 Apr 2025 20:59:42 +0530
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:http-internal/auth/health/live delay=0s timeout=5s period=10s #success=1 #failure=3
    Readiness:      http-get http://:http-internal/auth/health/ready delay=10s timeout=1s period=10s #success=1 #failure=3
    Startup:        http-get http://:http-internal/auth/health delay=15s timeout=1s period=5s #success=1 #failure=60
    Environment:
      KC_HTTP_RELATIVE_PATH:        /auth
      KC_CACHE:                     ispn
      KC_CACHE_STACK:               kubernetes
      KC_PROXY_HEADERS:             forwarded
      KC_HTTP_ENABLED:              true
      KC_DB:                        postgres
      KC_DB_URL_HOST:               kspg-postgresql.ns-sample.svc.cluster.local
      KC_DB_URL_PORT:               5432
      KC_DB_URL_DATABASE:           keycloak_db
      KC_DB_USERNAME:               keycloak_user
      KC_DB_PASSWORD:               <set to the key 'password' in secret 'keycloak-db-creds'>  Optional: false
      KC_METRICS_ENABLED:           true
      KC_HEALTH_ENABLED:            true
      KC_BOOTSTRAP_ADMIN_USERNAME:  admin
      KC_BOOTSTRAP_ADMIN_PASSWORD:  <set to the key 'password' in secret 'keycloak-admin-creds'>  Optional: false
      JAVA_OPTS_APPEND:             -Djgroups.dns.query=keycloak-keycloakx-headless
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9vp7t (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       True 
  ContainersReady             True 
  PodScheduled                True 
Volumes:
  kube-api-access-9vp7t:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  12m                default-scheduler  Successfully assigned ns-sample/keycloak-keycloakx-0 to minikube
  Normal   Pulled     12m                kubelet            Container image "docker.io/busybox:1.32" already present on machine
  Normal   Created    12m                kubelet            Created container: dbchecker
  Normal   Started    12m                kubelet            Started container dbchecker
  Normal   Pulled     12m                kubelet            Container image "quay.io/keycloak/keycloak:26.0.7" already present on machine
  Normal   Created    12m                kubelet            Created container: keycloak
  Normal   Started    12m                kubelet            Started container keycloak
  Warning  Unhealthy  11m (x7 over 12m)  kubelet            Startup probe failed: Get "http://10.244.1.28:9000/auth/health": dial tcp 10.244.1.28:9000: connect: connection refused
