### ISSUE TITLE
keycloak chart version 16.0.6 missing in index.yaml

### ISSUE THREAD

**Issue by grafjo** [codecentric/helm-charts#519]
Hi,

the keycloak chart version 16.0.6 is released and published here https://github.com/codecentric/helm-charts/releases/tag/keycloak-16.0.6 ... somehow this version is missing in https://codecentric.github.io/helm-charts/index.yaml, latest keycloak chart version is 16.0.5

**Comment by mprimeaux** [comment]
Hi all. Is there anyone working to resolve this issue?

**Comment by grafjo** [comment]
closing this issue regarding the available release of 17.0.x
