### ISSUE TITLE
Error: found in requirements.yaml, but missing in charts/ directory: postgresql

### ISSUE THREAD

**Issue by kapolos** [codecentric/helm-charts#52]
This is on Rancher 2.2.4 on a new cluster. I had been using the now deprecated Helm chart on a similar cluster without issues. But now that I tried using this one, it gives me this error.

![image](https://user-images.githubusercontent.com/10794126/59552270-68079980-8f8d-11e9-9af9-8aac6e42e9be.png)

These are the config options I supplied:

![image](https://user-images.githubusercontent.com/10794126/59552278-938a8400-8f8d-11e9-8d60-5c2fdde3c3ab.png)

I'm not very familiar with Helm, do you perhaps have an idea of what could be wrong?

**Comment by kapolos** [comment]
I tried installing from the old repo and that one works:

![image](https://user-images.githubusercontent.com/10794126/59552368-af425a00-8f8e-11e9-94eb-127c91ab64d2.png)

**Comment by unguiculus** [comment]
It looks like you need to run `helm repo update`.

**Comment by unguiculus** [comment]
Closing this now. It's not related to the chart itself but the way dependencies are handled in Helm. For general Helm questions, please check out the `helm-users` channel in Kubernetes Slack (https://kubernetes.slack.com).

**Comment by aviboru** [comment]
@kapolos - Might be delayed in responding, 
but i had same issue and was able to resolve it using [this reference](https://github.com/cloudposse/prometheus-to-cloudwatch/issues/10#issuecomment-446738814)

**Note:** Below are steps that worked for me in my local, haven't tested in rancher though.

1. Cloned latest keycloak helm chart repo
**⌘ git clone git@github.com:codecentric/helm-charts.git**

2. Ran helm install command and got below error
**⌘ helm install --name keycloak helm-charts/charts/keycloak/ --dry-run --debug**
```
[debug] Created tunnel using local port: '61320'
[debug] SERVER: "127.0.0.1:61320"
[debug] Original chart version: ""
[debug] CHART PATH: helm-charts/charts/keycloak
Error: found in requirements.yaml, but missing in charts/ directory: postgresql
```

3. Ran below update command per [this reference](https://github.com/cloudposse/prometheus-to-cloudwatch/issues/10#issuecomment-446738814)
**⌘  helm dependency update helm-charts/charts/keycloak**
```
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
        Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "stable" chart repository
Update Complete.
Saving 1 charts
Downloading postgresql from repo https://kubernetes-charts.storage.googleapis.com/
Deleting outdated charts
```

4. Run helm install command to see a successful response
**⌘  helm install --name keycloak helm-charts/charts/keycloak/ --dry-run --debug**
```
[debug] Created tunnel using local port: '61346'
[debug] SERVER: "127.0.0.1:61346"
[debug] Original chart version: ""
[debug] CHART PATH: helm-charts/charts/keycloak

NAME:   keycloak
REVISION: 1
RELEASED: Sat Aug 24 14:41:01 2019
CHART: keycloak-5.1.6
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
clusterDomain: cluster.local
init:
  image:
    pullPolicy: IfNotPresent
    repository: alpine
    tag: 3.9
...
...
...
```

**Comment by ahoehma** [comment]
@kapolos I come to here because I have currently the same problem :)
Can't install keycloak via ranger.
Do u solved this?

**Comment by donnydavis** [comment]
+1

**Comment by kapolos** [comment]
@ahoehma I have not, sorry.

**Comment by jakesyl** [comment]
Having the same issue

**Comment by rajsenthil** [comment]
> 1. helm dependency update helm-charts/charts/keycloak

This helped to solve the probelm. Thanks!

**Comment by fat8701** [comment]
use this url https://codecentric.github.io/helm-charts to add to rancher，dont  use https://github.com/codecentric/helm-charts. it solved.
