### ISSUE TITLE
Keycloak : allow to deploy ingress without host specified

### ISSUE THREAD

**Issue by olivierboudet** [codecentric/helm-charts#522]
In some cases, we need to deploy keycloak with ingress but without host specified, particularly in dev env.

In such a case, templating fails : 
```
  Error: template: keycloak/templates/ingress.yaml:36:19: executing "keycloak/templates/ingress.yaml" at <.host>: wrong type for value; expected string; got interface {}
```

If this issue is accepted, I can send a PR.

**Comment by thomasdarimont** [comment]
Hello @olivierboudet! Thanks for the issue. 

A PR would be welcome :)
