### ISSUE TITLE
Version 16.0.6 missing from Helm index

### ISSUE THREAD

**Issue by mprimeaux** [codecentric/helm-charts#524]
Is the exclusion of Keycloak version [16.0.6](https://github.com/codecentric/helm-charts/blob/7eb72ba6a383d85f3f87fd57e64ad55b600ed2c3/charts/keycloak/Chart.yaml#L3) from the Helm index [here](https://github.com/codecentric/helm-charts/blob/gh-pages/index.yaml) intentional? I see the released version correctly referenced in "Packages" but not in the related index.

**Comment by grafjo** [comment]
@mprimeaux see https://github.com/codecentric/helm-charts/issues/519

**Comment by mprimeaux** [comment]
@grafjo Thanks. I'll close this issue in lieu of #519
