### ISSUE TITLE
Keycloak HA - Failing to startup due to database exception

### ISSUE THREAD

**Issue by krp2** [codecentric/helm-charts#525]
We are experiencing an intermittent issue when we are trying to deploy Keycloak HA (2 replicas)
We can see database exception  in the logs which says some tables are already existing. But Database was clean when Keycloak was attempted to start. Attaching the logs of both replicas for reference. 
Can you please suggest what could be the reason for this?

[keycloak-1.log](https://github.com/codecentric/helm-charts/files/7914041/keycloak-1.log)
[keycloak-0.log](https://github.com/codecentric/helm-charts/files/7914043/keycloak-0.log)

**Comment by mgs255** [comment]
Hi.  I ran into a similar issue recently with our dev keycloak instances.  That error may be a red herring. 

I got around this when  I bumped both the cpu and memory requests and the pods then started successfully.  There is a section in the read me on how to pass additional JVM options.  I added Xmx and Xms options there.
