### ISSUE TITLE
[keycloak] extraEnv is defined as string in values.schema.json

### ISSUE THREAD

**Issue by torstenwerner** [codecentric/helm-charts#535]
Why is extraEnv defined to be a string only? An array would work as well and would be more natural. I propose to change the type to be anyOf string or array. An array of objects with properties name and value to be more precise.

**Comment by joscabmar** [comment]
My workaround was:
`extraEnv: |
  - name: KEYCLOAK_LOGLEVEL
    value: DEBUG
  - name: WILDFLY_LOGLEVEL
    value: DEBUG`

**Comment by mircohaug** [comment]
Hi,
`extraEnv` and other keys are defined as strings to allow the usage of templates inside this sections. For an example see [this](https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#changing-the-context-path). For more information about the usage of the `tpl` function in this chart see the [README](https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#usage-of-the-tpl-function)

Cheers
