### ISSUE TITLE
cant create admin user

### ISSUE THREAD

**Issue by gobinathn-aetna** [codecentric/helm-charts#552]
Keycloak pod crashes with below error. i'm using  chart version 16.1.0 and keycloak version 16.1.1

error:
------

2022-03-03T02:40:55.388812014Z
/opt/jboss/keycloak/bin/add-user-keycloak.sh: line 75: 29 Killed "java" -Dkeycloak.hostname.provider=request -DAPP_ENV=${CLUSTER_ENV} --add-exports=java.desktop/sun.awt=ALL-UNNAMED --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.management/javax.management=ALL-UNNAMED --add-opens=java.naming/javax.naming=ALL-UNNAMED -jar "/opt/jboss/keycloak/jboss-modules.jar" -mp "/opt/jboss/keycloak/modules" org.keycloak.keycloak-wildfly-adduser "$@"

**values.yml entry**

 extraEnv: |
    - name: KEYCLOAK_LOGLEVEL
      value: INFO
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: KEYCLOAK_USER
      value: "admin"
    - name: KEYCLOAK_PASSWORD
      value: "******"

**Comment by frippe75** [comment]
Same issue...  Tried running the 
`kubectl exec -n keycloak pods/keycloak-0 -- /opt/jboss/keycloak/bin/add-user-keycloak.sh -u admin -p <password>`

But that creates a file under /opt/jboss/keycloak/standalone/configuration which is not persisted during next boot when running under non-docker password would get picked up ??

So struggled for a day simply trying to automate to a place where the admin user exists right of the bat.
