### ISSUE TITLE
Error in ingress template

### ISSUE THREAD

**Issue by meiko** [codecentric/helm-charts#556]
When compiling the Chart with ingress enabled:
`Error: INSTALLATION FAILED: Ingress in version "v1" cannot be handled as a Ingress: json: cannot unmarshal number into Go struct field ServiceBackendPort.spec.rules.http.paths.backend.service.port.name of type string`
The reason can be found here: [ingress.yaml line 60](https://github.com/codecentric/helm-charts/blob/58d18febb7312113e579fb1b00d0a2e5a14a6f0f/charts/keycloak/templates/ingress.yaml#L60)

Fix: `number: {{ $ingress.servicePort }}`

**Comment by meiko** [comment]
i had to use `http`

**Comment by rlanore** [comment]
Hi, why this PR are not merge ? we hit this bug into our deployement of keycloaks. 
What do you mean by use http @meiko 
thanks
