### ISSUE TITLE
Keycloak: wait-for-postgres init Container does not allow to specify resources

### ISSUE THREAD

**Issue by OlliL** [codecentric/helm-charts#57]
We have a cluster environment where limit and request settings for CPU and memory are enforced for every container. This is of course possible for the keycloak container itself as well as for the embedded postgresql helm chart/container.
Unfortunally it is not possible for the init container wait-for-postgres which is automatically enabled when deployPostgres is enabled.

Keycloak will not start up claiming that limits and requests have to be specified. 

``create Pod mp-login-keycloak-0 in StatefulSet mp-login-keycloak failed error: pods "mp-login-keycloak-0" is forbidden: failed quota: default-4jmm8: must specify limits.cpu,limits.memory,requests.cpu,requests.memory``

Manually modifying the installed sidecar wait-for-postgres container after the helm chart installation and adding ressource limits + requests makes keekloack come up finally.

Please add a values.yaml possibility to be able to specify resources for the init Container.

**Comment by unguiculus** [comment]
Thanks for reporting this. I'll add it to my list of things to add. Feel free to submit a PR yourself.
