### ISSUE TITLE
[keycloakx] doc typo mixup between db and admin username/password 

### ISSUE THREAD

**Issue by thomas-riccardi** [codecentric/helm-charts#605]
https://github.com/codecentric/helm-charts/tree/master/charts/keycloakx#creating-a-keycloak-admin-user

The `keycloakx` README talks about admin user creation, but mentions environment variables for the database: 
- `KC_DB_USERNAME`
- `KC_DB_PASSWORD`

I believe the correct env vars are:
- `KEYCLOAK_ADMIN`
- `KEYCLOAK_ADMIN_PASSWORD`

source: https://www.keycloak.org/server/containers#_provide_initial_admin_credentials_when_running_in_a_container

**Comment by thomas-riccardi** [comment]
not stale

**Comment by thomas-riccardi** [comment]
not stale

**Comment by grieshaber** [comment]
Corresponding PR of @wilmardo is merged. This PR resolves the misconception from the README.

**Comment by thomas-riccardi** [comment]
fixed in #624 for reference.
