### ISSUE TITLE
[keycloak] PodDisruptionBudget API selection not working on GKE cluster

### ISSUE THREAD

**Issue by dides82** [codecentric/helm-charts#607]
Hi all,

I am working on removing API deprecation warnings of keycloak helm-generated manifests (chart version 17.0.3) and stumbled upon following warning:
```
pluto detect-helm -o wide
NAME                NAMESPACE   KIND                  VERSION                     REPLACEMENT            DEPRECATED   DEPRECATED IN   REMOVED   REMOVED IN  
keycloak/keycloak   keycloak    PodDisruptionBudget   policy/v1beta1              policy/v1              true         v1.21.0         false     v1.25.0
```

The following semver comparison in the PodDisruptionBudget template does not work when working on a GKE cluster: 
```
{{- if semverCompare ">=1.21.0" .Capabilities.KubeVersion.GitVersion }}
```
Server version in GKE is of the form 'vX.Y.Z-gke.number' which is interpreted as a pre-release by the helm function `semverCompare` (see [doc](https://helm.sh/docs/chart_template_guide/function_list/#working-with-prerelease-versions))
```
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11-gke.1100", GitCommit:"20da4c21b3a6b1a56ff6ad5ecb7dee013aaf1b83", GitTreeState:"clean", BuildDate:"2022-04-01T09:40:07Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
```
 
Generated PodDisruptionBudget manifest still uses policy/v1beta1 API where it should use  policy/v1 API.

I found 2 workarounds :

- either forcing pre-release checks with the following code :
```
{{- if semverCompare ">=1.21.0-0" .Capabilities.KubeVersion.GitVersion }}
```
- or using the .Capabilities.APIVersions object:
```
{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
{{ else }}
apiVersion: policy/v1beta1
{{ end -}}
```

I personally prefer the second solution 😄 

Tested the proposed workaround on a 1.21 GKE cluster and a 1.20.7 Minikube cluster and the correct APIs are used.

**Comment by andrew-landsverk-win** [comment]
I just wanted to report that this is also not working on MicroK8s clusters.
