### ISSUE TITLE
microk8s helm3 lint ./charts/* error

### ISSUE THREAD

**Issue by vigouredelaruse** [codecentric/helm-charts#609]
hello- just reporting the current lint output on microk8s helm3

sudo microk8s helm3 lint ./charts/*
 Linting ./charts/keycloak
[ERROR] templates/: template: keycloak/templates/statefulset.yaml:59:48: executing "keycloak/templates/statefulset.yaml" at <include "keycloak.postgresql.fullname" .>: error calling include: template: keycloak/templates/_helpers.tpl:68:3: executing "keycloak.postgresql.fullname" at <include "postgresql.primary.fullname" $postgresContext>: error calling include: template: no template "postgresql.primary.fullname" associated with template "gotpl"
[WARNING] /devops/gits/wizardcontroller/codecentric-helm-charts/charts/keycloak: chart directory is missing these dependencies: postgresql

==> Linting ./charts/keycloakx

==> Linting ./charts/mailhog

Error: 3 chart(s) linted, 1 chart(s) failed

regards

**Comment by grieshaber** [comment]
This should be resolved - the used postgres-version wasn't available anymore, but was dumped with #618. I'd therefore close this issue.
