### ISSUE TITLE
keycloakx url is not redirecting to /auth

### ISSUE THREAD

**Issue by nagender1005** [codecentric/helm-charts#612]
we replaced keycloak with keycloakx using helm charts 1.3.2, "https://keycloakx.example.com" is not working, its working only if we add "/auth" at the end like "https://keycloakx.example.com/auth", the base url is not redirecting to /auth which used to work in keycloak automatically, but not happening in keycloakX.

we tried changing  KC_HTTP_RELATIVE_PATH="/auth"  to KC_HTTP_RELATIVE_PATH="/" and KC_HTTP_RELATIVE_PATH="/*" etc etc, but no luck. 

Can someone help here ? Thanks in advance.

**Comment by revolunet** [comment]
`/auth` is not more necessary

**Comment by fbreckle** [comment]
Try putting
```
http:
  relativePath: '/'
```
in the values.yml

**Comment by nagender1005** [comment]
@fbreckle thanks it worked.. 

closing this.
