### ISSUE TITLE
Do we have terraform provider for keycloakX just like keycloak ?

### ISSUE THREAD

**Issue by nagender1005** [codecentric/helm-charts#614]
Do we have terraform provider for keycloakX just like keycloak ?

**Comment by MarS919** [comment]
As the Keycloak REST Admin API hasn't changed, there is no need for a new version of the terraform provider. See https://github.com/mrparkers/terraform-provider-keycloak#a-note-for-users-of-the-new-quarkus-distribution

**Comment by grieshaber** [comment]
Thanks @MarS919 for the information. I'll close this issue then.
