### ISSUE TITLE
Difference between keycloak and keycloakx

### ISSUE THREAD

**Issue by GretUp** [codecentric/helm-charts#616]
I see that keycloakx is the logical successor of the Wildfly based keycloak chart.
But what is the difference? In which sense it is the "logical successor"?
When should we use keycloak as opposed to keycloakx?

**Comment by SergNikitinSharpDev** [comment]
keycloakx uses Quarkus. You should consider migrating to keycloakx in case you want to update keycloak in the future, as Wildfly support for keycloak is deprecated since June 2022
