### ISSUE TITLE
Project still mantained?

### ISSUE THREAD

**Issue by eyenx** [codecentric/helm-charts#620]
Is this project still mantained? Asking because PR get opened but nobody is reacting on them Example: #488  and after a while they get closed.

We had a production incident because of the Chart not templating the service used for postgresql-ha correctly. Please mantain your code!

**Comment by grieshaber** [comment]
Hey @eyenx,

in general, this project is still maintained. But we had some changes to the maintainers-team and certainly some busy weeks with our daily work. We'll try to increase our awareness for new PRs and Reviews for them, but won't have time to resolve issues ourselfs mostlikely.

Is your PR still relevant? Would you mind reopening it? I'll then try to find time for a review.

**Comment by grieshaber** [comment]
.. i have reopended the PR. Would be great if you could do the rebase and ping me once your through!
