### ISSUE TITLE
[keycloakx] Bug: health check depends on metrics.enabled flag

### ISSUE THREAD

**Issue by grieshaber** [codecentric/helm-charts#636]
Instead of reliying on the newly introduced `health.enabled` (https://github.com/codecentric/helm-charts/pull/592/files) flag, the HEALTH endpoint is enabled via `metrics.enabled` flag. 

This might lead to confusion and should be fixed.

**Comment by Footur** [comment]
@grieshaber I've published a pullrequest regarding this issue (#638).

**Comment by grieshaber** [comment]
.. after reading the release notes of keycloak 19, i realized: relying on `metrics.enabled` was not totally wrong, but also not enough.
```
The health/ready endpoint used for readiness probes still checks for a working database connection. Make sure you have not only health-enabled=true but also metrics-enabled=true set in your configuration, to enable the database check, resulting in an effective readiness probe. It will return HTTP status-code 503 and a status of DOWN when the database connection is not in a healthy state.
```
So in order to have _fully_ functional readinessChecks, we need both, `health` and `metrics` endpoints enabled.

**Comment by Footur** [comment]
@grieshaber Maybe we should write a note in the README?

**Comment by grieshaber** [comment]
@Footur yes, that is definetly a good idea. I'm just thinking about a "technical" solution as well. As we have the if clause for health enabled in place, should we maybe add the check for health and metrics to the readnessProbe?

**Comment by grieshaber** [comment]
Thanks to @Footur the latest idea (Readme + technical feature gate) will be resolved with https://github.com/codecentric/helm-charts/pull/633.

**Comment by grieshaber** [comment]
Resolved.
