### ISSUE TITLE
How to add admin user to a realm

### ISSUE THREAD

**Issue by RAbraham** [codecentric/helm-charts#64]
Hi,
I apologize if this is more a keycloak question then k8 question, but I'm trying to add an admin user to a realm after installing keycloak. I have tried this:

```
[jboss@keycloak-0 keycloak]$ bin/add-user-keycloak.sh -r 15rock -u admin-15rock -p <mypwd>
Added 'admin-15rock' to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json', restart server to load user
```
How do I restart the server? I tried deleting the pod so that the stateful set would start the pod again but that did not create the admin user for that realm. If you have any pointers, I would be grateful.

**Comment by unguiculus** [comment]
It looks like you did it correctly. What database did you use?

**Comment by RAbraham** [comment]
Thanks for replying. I'm using the GCP SQL proxy side car to connect to a GCP SQL Cloud Instance(PostgreSQL).

**Comment by cablespaghetti** [comment]
I have this same issue. Previously if I set keycloak.password this all happened for me. Now I get prompted to run keycloak-add-user which I can do, but as I don't have a persistent volume mounted where it spits out its JSON file if I restart the container so the Keycloak startup process can pick up the JSON file, it is no longer there.

I'm digging into at what point this functionality got broken.

**Comment by cablespaghetti** [comment]
Ah I think it was this commit. We're still on Keycloak 5, so I guess that KEYCLOAK_PASSWORD_FILE is a Keycloak 7 thing:
https://github.com/codecentric/helm-charts/commit/6a2c0275d35d2d13c5a293ce0950241ba423be75

**Comment by unguiculus** [comment]
That could very well be it. You generally should not downgrade Keycloak versions. that's likely to not work. If you need to use an older version, stay with an older version of the chart.

**Comment by PavelJacobo** [comment]
The same issue happens to me. I have PVs, I use MySQL as db.

[jboss@dev-keycloak-0 bin]$ ./add-user-keycloak.sh -r SDS -u admin -p <password>
Added 'admin' to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json', restart server to load user
