### ISSUE TITLE
Unable to scrape metrics for keycloak - Error: Connection refused

### ISSUE THREAD

**Issue by faizanahmad055** [codecentric/helm-charts#654]
I have the following env enabled.

```yaml
extraEnv: |
  - name: KEYCLOAK_STATISTICS
    value: all
```
But the Prometheus operator is still not able to scrape the metrics. Inside the pod 

```bash
curl localhost:9990/metrics
```
works but 

```bash
curl <pod-ip>:9990/metrics
```

doesn't work and gives out a connection refuse error.

```bash
curl: (7) Failed to connect to <pod-ip> port 9990: Connection refused
```
My issue is the same as #436, but I have also added the above-mentioned env to expose metrics. Anyone can help me with this?

**Comment by dhofstetter** [comment]
The same applies to me, it works if I do a port-forwarding to my Keycloak management http service on 9990.

But If my prometheus instance try to reach the metrics it won't work.
