### ISSUE TITLE
Can we use this helm chart for deploying Quarkus based Keycloak?

### ISSUE THREAD

**Issue by bjethwan** [codecentric/helm-charts#659]
Can we use this helm chart for deploying Quarkus-based Keycloak?
The git readme doesn't talk about Quarkus-based Keycloak.
And image.tag doc just states that "Overrides the Keycloak image tag whose default is the chart version. Note versions after 16.1.1 need to use the -legacy suffix, e.g. 17.0.1-legacy"

**Comment by mrszop** [comment]
Hello bjethwan,

you can use the [keycloakx helm chart](https://artifacthub.io/packages/helm/codecentric/keycloakx) and [here](https://github.com/codecentric/helm-charts/tree/master/charts/keycloakx)

Cheers
