### ISSUE TITLE
Error about "Cookie not found. Please make sure cookies are enabled in your browser."

### ISSUE THREAD

**Issue by chihhaohuang** [codecentric/helm-charts#662]
I use keyloak with a Azure B2C as default IDP.
When session expired (10 hours I think), I would be redirect to IDP login page.
But after re-logged in, the error showed up.
Checked the code from keycloak and it comes from KC_RESTART cookie not found.
And when I checked cookie, I cannot find that cookie.
(I have KEYCLOAK_SESSION, KEYCLOAK_IDENTITY, AUTH_SESSION_ID, etc.)
Did I miss any configuration?

**Comment by fbede4** [comment]
hi, what was the issue in your case?

**Comment by ujjavalraval** [comment]
have u find any solution regarding it.
