### ISSUE TITLE
Your repository is not working for a couple of days it seems...

### ISSUE THREAD

**Issue by zaks** [codecentric/helm-charts#692]
$ helm repo add --debug --force-update --insecure-skip-tls-verify codecentric https://codecentric.github.io/helm-charts

Error: looks like "https://codecentric.github.io/helm-charts" is not a valid chart repository or cannot be reached: Get "https://codecentric.github.io/helm-charts/index.yaml": http: server gave HTTP response to HTTPS client
helm.go:84: [debug] Get "https://codecentric.github.io/helm-charts/index.yaml": http: server gave HTTP response to HTTPS client
looks like "https://codecentric.github.io/helm-charts" is not a valid chart repository or cannot be reached
main.(*repoAddOptions).run
        helm.sh/helm/v3/cmd/helm/repo_add.go:211
main.newRepoAddCmd.func1
        helm.sh/helm/v3/cmd/helm/repo_add.go:82
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.5.0/command.go:872
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.5.0/command.go:990
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.5.0/command.go:918
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_arm64.s:1172

**Comment by der-eismann** [comment]
Works fine for me, maybe GitHub had an issue.

**Comment by bradym** [comment]
I'm seeing the same thing from my home internet connection, but it works fine from another server. Seems like an ISP issue.

As check I used curl to see what would happen in both locations. 

Home:

```
$ curl -vI https://codecentric.github.io/helm-charts
*   Trying 185.199.110.153:443...
* Connected to codecentric.github.io (185.199.110.153) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* (5454) (IN), , Unknown (72):
* error:0A00010B:SSL routines::wrong version number
* Closing connection 0
curl: (35) error:0A00010B:SSL routines::wrong version number
```

Remote:

```
$ curl -I https://codecentric.github.io/helm-charts
HTTP/2 301 
server: GitHub.com
content-type: text/html
permissions-policy: interest-cohort=()
location: https://codecentric.github.io/helm-charts/
x-github-request-id: 8780:549F:1B4E51:1FB2FD:63F7BA15
accept-ranges: bytes
date: Thu, 23 Feb 2023 19:10:13 GMT
via: 1.1 varnish
age: 0
x-served-by: cache-sna10723-LGB
x-cache: MISS
x-cache-hits: 0
x-timer: S1677179414.841917,VS0,VE101
vary: Accept-Encoding
x-fastly-request-id: 74980fda9db5de7caea1c63d02a903e8122f0e47
content-length: 162
```

**Comment by grieshaber** [comment]
As it seems to be an issue with GIthub or ISPs, i'll close this one.

**Comment by bradym** [comment]
For anyone else who may be having issues.

Turns out the "Malicious Sites Blocking" feature of "AiProtection" on my ASUS router is blocking codecentric.github.io claiming it's a phishing site. When I disable "Malicious Sites Blocking" the issue goes away. I'll look into how to report this false positive to Trend Micro.

**Comment by bradym** [comment]
I posted a request at https://global.sitesafety.trendmicro.com/ to remove the phishing classification.
