### ISSUE TITLE
how to deploy this helm chart with existing mysql?

### ISSUE THREAD

**Issue by justmike1** [codecentric/helm-charts#697]
So currently I deploy this helm chart as is, with the postgresql provided, but I already deploy mysql for my app and would like to keep it (and not migrate to postgresql), is there a way to set values to connect to mysql instead of postgresql? or do I need to create a new docker image to support it

**Comment by ismailyenigul** [comment]
Hi,
No you dont have to use postgresql
set `database.vendor` as mysql
see https://www.keycloak.org/server/db
