### ISSUE TITLE
How to upgrade to keycloak version 21.0.X with helm chart

### ISSUE THREAD

**Issue by taragurung** [codecentric/helm-charts#699]
I am running the helm chart **keycloak-18.2.1** upgrading it to the **keycloak-18.4.0** also has the same keycloak version.

I could not find the right Tags that is available to upgrade to lated KeyCloak version. 

**Is it that, the helm chart is not available to upgrade to latest keycloak version 21.X.X ?**

**Comment by ismailyenigul** [comment]
just upgraded my keycloakx from 19 to 21 by setting keycloak by setting setting  tag: "21.0.2" in values.yml
Don't forget to take database backup before major upgrade.

**Comment by grieshaber** [comment]
You cannot upgrade the old Chart to AppVersion > 20. as keycloaked dropped the support for Wildfly (which is used / shipped with the old keycloak installation). For a Keycloak Version > 20 you need to use the keycloakx Chart and migrate.
