### ISSUE TITLE
KeycloakX Helm chart 2.2.0 not in index.

### ISSUE THREAD

**Issue by mprimeaux** [codecentric/helm-charts#705]
I do not see version `2.2.0` of the [Keycloakx](https://github.com/codecentric/helm-charts/tree/master/charts/keycloakx) Helm chart in the index.

```shell
helm repo add codecentric https://codecentric.github.io/helm-charts
helm repo update
helm search repo keycloakx
NAME                 	CHART VERSION	APP VERSION	DESCRIPTION
codecentric/keycloakx	2.1.1        	20.0.3     	Keycloak.X - Open Source Identity and Access Ma..
```

The latest chart seems to be [2.2.0](https://github.com/codecentric/helm-charts/blob/05d432f62a639f972ae7e8052c070fb198245b87/charts/keycloakx/Chart.yaml#L3).

**Comment by grieshaber** [comment]
Found the issue - the upload functionality failed because one of the charts had issues. I'm on it :)

**Comment by mprimeaux** [comment]
@grieshaber Any updates on the resolution? Thanks much for your help.

**Comment by grieshaber** [comment]
unfortunately not yet - issue is, that he postgresql version used in keycloak chart is not available anymore and therefore the packaging of the chart does not work and breaks the releaser job. Upgrade the postgres to a newer version did not work "out of the box" and needs more time. I'll check, whether i can make the old postgres available again somehow..

Sorry for any inconvenience

**Comment by grieshaber** [comment]
Finally available, fixed / changed the release action.
