### ISSUE TITLE
Keycloak 21.x - Multiple replicas lead to 404 errors when accessing admin panel

### ISSUE THREAD

**Issue by cvallesi-kainos** [codecentric/helm-charts#717]
Hey there, I was testing this chart with multiple replicas and noticed a behaviour similar to what is described here:

https://github.com/keycloak/keycloak/issues/12719#issuecomment-1263610724

Is there a known option/configuration I'm missing that would resolve that issue for this chart?

**Comment by albertschwarzkopf** [comment]
Same here

**Comment by albertschwarzkopf** [comment]
Solved in my case. I had to add the following annotation to my Traefik Ingress:

`ingress.kubernetes.io/whitelist-x-forwarded-for: "true"`
