### ISSUE TITLE
Unable to install Keycloak

### ISSUE THREAD

**Issue by Sj1218305** [codecentric/helm-charts#719]
Ran the command `helm install keycloak codecentric/keycloak`.
But, below is the status of both the pods - 

keycloak-0                           0/1     Init:0/1                 0                25m
keycloak-postgresql-0                0/1     CrashLoopBackOff         9 (4m7s ago)     25m

Here are the logs of both the pods 
- keycloak-0
Defaulted container "keycloak" out of: keycloak, pgchecker (init)
Error from server (BadRequest): container "keycloak" in pod "keycloak-0" is waiting to start: PodInitializing
- keycloak-postgresql-0
exec /opt/bitnami/scripts/postgresql/entrypoint.sh: exec format error

**Comment by ajmalkhalil** [comment]
Hello @Sj1218305, How did you resolve this issue. I am getting same issue. Can you please help?
Thanks
