### ISSUE TITLE
Template postgresql.fullname not defined

### ISSUE THREAD

**Issue by wuerzelchen** [codecentric/helm-charts#73]
When you set .Values.keycloak.persistence.deployPostgres: true

There is an error in the _helpers.tpl file, with an undefined template: "postgresql.fullname"
Line 76 in _helpers.tpl

**Comment by unguiculus** [comment]
Please be more specific and provide steps to reproduced. What chart version are you using? What's the Helm output etc.

**Comment by wuerzelchen** [comment]
It was probably a typo somewhere. I tried it with a fresh values.yaml and now I cannot reproduce it anymore. Thanks for your response.
