### ISSUE TITLE
Version Upgrade

### ISSUE THREAD

**Issue by Hemant0601** [codecentric/helm-charts#741]
The version in the chart showing

in the file Chart.yaml

`apiVersion: v2
appVersion: 17.0.1-legacy`

However the official version of keycloak is 23.0.4 , reference from here [23.0.4](https://www.keycloak.org/downloads-archive.html)

How to upgrade to the latest version and how to do it.

**Comment by megian** [comment]
Use the `keycloakx` rather than the `keycloak` helm chart.

**Comment by KlavsKlavsen** [comment]
keycloakx has an old version still.. it says appversion 22.0.4 - when latest keycloak release is 23.04.. Is it a typo or ?

**Comment by megian** [comment]
Yes, but there are no breaking config changes to my knowledge. Just override the image to the newest image tag.
