### ISSUE TITLE
Support for external database?

### ISSUE THREAD

**Issue by buaydin** [codecentric/helm-charts#755]
From the values.yaml I couldn't find HowI can integrate Postgresql Server on the specific host. It's not supported or am I missing something? I don't want to create postgresql pod or use H2 database. I have my own postgresql server that I want to integrate.

**Comment by andrew-landsverk-win** [comment]
You can set this in valyes.yaml:

`
database:
  vendor: mariadb
  hostname: 192.168.X.X
  port: 3306
  database: keycloak
  username: keycloak
`

There should be a way to pull the password for the DB from a secret/environment variable, I seem to have 2, probably from a previous version:

DB_PASSWORD
or
KC_DB_PASSWORD

**Comment by buaydin** [comment]
hi @andrew-landsverk-win there is no database section in values.yaml. I'm confused.
 In postgresql bitnami subchart it needs to be done like that I think;

postgresql:
  enabled: false
  host: Mypostgredbhost
  postgresqlUsername: keycloak
  postgresqlPassword: keycloak
  postgresqlDatabase: keycloak

But it's not working for codecentric keycloak chart. It connects to h2 database.

**Comment by andrew-landsverk-win** [comment]
Ohh, I was referring to the keycloakx chart, are you using the keycloak (non-x) chart? For keycloakX, the relevant section is here: https://github.com/codecentric/helm-charts/blob/master/charts/keycloakx/values.yaml#L389
