### ISSUE TITLE
Bind change preventing port forward

### ISSUE THREAD

**Issue by StephLabuschgane** [codecentric/helm-charts#76]
Hi, since this mornings release we are unable to port forward, resulting in a few environments failing.

This seems to be related to the change you made, from the Keycloak logs:

10:55:41,554 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0006: Undertow HTTP listener default listening on 100.96.7.6:8080

We rolled back to version 5.1.1, from the Keycloak logs:

12:13:44,442 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0006: Undertow HTTP listener default listening on 0.0.0.0:8080

Version 5.1.2 does not work. Anything we need to do to make this work on the latest version?

**Comment by unguiculus** [comment]
Thanks for reporting this. I'll revert the changes for now until I find a better solution.
