### ISSUE TITLE
proxy definition is deprecated after updating image to 24.0.3. The  proxy-headers should be used instead.

### ISSUE THREAD

**Issue by koi8** [codecentric/helm-charts#773]
```
2024-05-18 20:09:59,756 WARN  [org.key.qua.run.cli.Picocli] (main) The following used options or option values are DEPRECATED and will be removed in a future release:
    - proxy: Use proxy-headers.
```

More details in documentation - https://www.keycloak.org/docs/latest/upgrading/index.html#deprecated-proxy-option

**Comment by AMontagu** [comment]
Look like it has been changed in the latest release (2.4.2). 
Please be aware the last release may have some issue. 
You cna look at: https://github.com/codecentric/helm-charts/issues/779
