### ISSUE TITLE
codecentric helm repo has entry for only "jenkins"

### ISSUE THREAD

**Issue by vsomaai** [codecentric/helm-charts#81]
codecentric helm repo can pull only jenkins chart. Keycloak is not available through repo. Is keycloak available on this repo?
Looking at the following file as referenace
https://codecentric.github.io/helm-charts/index.yaml

`apiVersion: v1
entries:
  jenkins:
  - apiVersion: v1
    appVersion: 2.176.2
    created: "2019-07-22T19:58:42.151419723Z"
    description: The leading open source automation server
    digest: c677eb97fec4b54f6abc4bfbd1c21c5bbb4fee94a0e6680183ba661ab654e251
    home: https://jenkins.io/
    icon: https://wiki.jenkins-ci.org/download/attachments/2916393/logo.png
    keywords:
    - ci
    - continuous integration
    - continuous delivery
    - continuous deployment
    - devops
    - automation
    maintainers:
    - email: unguiculus@gmail.com
      name: unguiculus
    name: jenkins
    sources:
    - https://github.com/codecentric/helm-charts
    - https://github.com/jenkinsci/jenkins
    - https://github.com/jenkinsci/docker
    - https://github.com/jenkinsci/docker-jnlp-slave
    urls:
    - https://github.com/codecentric/helm-charts/releases/download/jenkins-1.4.1/jenkins-1.4.1.tgz
    version: 1.4.1
generated: "2019-07-22T19:58:41.936207039Z"`

**Comment by swistaczek** [comment]
Same issue right now.

**Comment by Keithsc** [comment]
Same issue

**Comment by OlehMartushevskyi** [comment]
Same issue

**Comment by hnicke** [comment]
Same issue here

**Comment by martinkubrak** [comment]
Same problem here

**Comment by unguiculus** [comment]
Thanks for reporting this. Yesterdays update seems to have messed up the repo. I'll have a look.

**Comment by unguiculus** [comment]
I quickly tried to quickly fix it but am not sure it works. I'm in a workshop the whole day and will look at it later again. Sorry about that.

**Comment by umitseremet** [comment]
It works! thanks for action

**Comment by unguiculus** [comment]
Yes, I just figured. I had a caching issue. I'll look at the underliying issue tonight.
