### ISSUE TITLE
Realm Config Updates

### ISSUE THREAD

**Issue by bsingr** [codecentric/helm-charts#85]
Initially the realm json file is successfully imported. But when the realm json is changed and a cluster node is restarted the changes are not reflected. In the logs it states:

`Realm 'foo' already exists. Import skipped`

Do we do something wrong? Or how do you deal with that?

**Comment by unguiculus** [comment]
Please check the docs:
https://www.keycloak.org/docs/latest/server_admin/index.html#_export_import

You probably need to set `-Dkeycloak.migration.strategy=OVERWRITE_EXISTING`.
