### ISSUE TITLE
KEYCLOAK_LOGLEVEL is not used

### ISSUE THREAD

**Issue by strowk** [codecentric/helm-charts#93]
Code completely ignores 'KEYCLOAK_LOGLEVEL'. It's mentioned only in documentation and comment. 

https://github.com/codecentric/helm-charts/search?q=KEYCLOAK_LOGLEVEL&unscoped_q=KEYCLOAK_LOGLEVEL

**Comment by unguiculus** [comment]
Thanks for reporting this. It is indeed no longer used and should be removed from the documentation. Use `WILDFLY_LOGLEVEL` instead.
