### ISSUE TITLE
[Keycloak] Ability to override persistence information with env variables

### ISSUE THREAD

**Issue by seboudry** [codecentric/helm-charts#94]
Hi!

PostgreSQL connection configuration is available on my clusters trough one configmap (for PostgreSQL instance URL and port) and a secret (for database, user and password).
So, I want to use env `valueFrom` to define persistence configuration for my Keycloak Helm release. I give them on `keycloak.extraEnv` chart parameter.

This result with duplicate `DB_*` env entries on final YAML (ones defined trough `keycloak.dbEnvVars` and others with `keycloak.extraEnv`).
Sometimes, Helm (or Kubernetes) complains with this error:
```
Error: UPGRADE FAILED: The order in patch list:
[map[name:DB_PORT value:<nil> valueFrom:map[configMapKeyRef:map[key:postgres-port name:postgres-server]]] map[name:DB_PORT value:5432 valueFrom:<nil>] map[name:DB_DATABASE value:<nil> valueFrom:map[secretKeyRef:map[key:postgres-database name:postgres-keycloak]]] map[name:DB_DATABASE value:keycloak valueFrom:<nil>] map[name:DB_USER value:<nil> valueFrom:map[secretKeyRef:map[name:postgres-keycloak key:postgres-username]]] map[valueFrom:<nil> name:DB_USER value:keycloak] map[$patch:delete name:JGROUPS_DISCOVERY_PROPERTIES] map[$patch:delete name:JGROUPS_DISCOVERY_PROTOCOL] map[name:KEYCLOAK_SERVICE_DNS_NAME $patch:delete]]
doesn't match $setElementOrder list:
[map[name:KEYCLOAK_USER] map[name:KEYCLOAK_PASSWORD_FILE] map[name:DB_VENDOR] map[name:DB_ADDR] map[name:DB_PORT] map[name:DB_DATABASE] map[name:DB_USER] map[name:DB_PASSWORD] map[name:KEYCLOAK_LOGLEVEL] map[name:PROXY_ADDRESS_FORWARDING] map[name:DB_ADDR] map[name:DB_PORT] map[name:KEYCLOAK_JDBC_PARAMS] map[name:DB_DATABASE] map[name:DB_USER] map[name:DB_PASSWORD]]

```

Possible solutions:
- only set Keycloak's `DB_*` env vars from parameters default values if `deployPostgres` is used
- define a chart parameter to bypass `keycloak.dbEnvVars` generation
- define multiple new chart parameters to define persistence values to use a key in a configmap/secret

First two solutions let user define `DB_*` env vars by himself.
Last solution generate a lot of parameters and introduce some complexity on [`keycloak.dbEnvVars` helper](https://github.com/codecentric/helm-charts/blob/keycloak-5.1.5/charts/keycloak/templates/_helpers.tpl#L137).

What do you think of it?

**Comment by unguiculus** [comment]
Thanks for the request. I'll have to think this through.

**Comment by unguiculus** [comment]
Are you still having issue with this or can this be closed?
