### ISSUE TITLE
[Keycloak][Question] Running command in kcadm after keycloak is started?

### ISSUE THREAD

**Issue by aperullo** [codecentric/helm-charts#95]
I am looking to run a command to add an LDAP to keycloak so that it can be done as part of a deploy process rather than having to be run manually. I've managed to assemble a `kcadm.sh` command to do so:

```
./kcadm.sh create components -r master \
-s name=ldap \
-s providerId=ldap \
-s providerType=org.keycloak.storage.UserStorageProvider \
-s parentId=master  \
-s 'config.enabled=["true"]' \
-s 'config.priority=["0"]' \
...
``` 

I'm struggling to figure out a way to run this. I think it has to be run *after* keycloak is up and running, so **init containers** are no good.

I saw the **wildfly custom scripts** parameter as well, but I don't know when they actually run. Also the command I want to run isn't for the wildfly scripting language just for `kcadm.sh`.

What method could I go about using to accomplish this?

**Comment by unguiculus** [comment]
Custom scripts can be any executable scripts, no just CLI scripts. However, they are run right before Keycloak is started.

See:
* https://github.com/jboss-dockerfiles/keycloak/tree/master/server#running-custom-scripts-on-startup
* https://github.com/jboss-dockerfiles/keycloak/blob/master/server/tools/autorun.sh
* https://github.com/jboss-dockerfiles/keycloak/blob/master/server/tools/docker-entrypoint.sh#L196

Another option could be to use a lifecycle hook. However, Kubernetes does not guarantee a pod ready before executing a hook, so you'll have to add some logic that waits for Keycloak to be up and running if you need that.

**Comment by aperullo** [comment]
I tried those and had no success with such methods. I did find this link inside some old keycloak mailing list entry. 

https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.0/html/server_administration_guide/export_import

Ended up setting up keycloak how I wanted, then exporting the config and including it as a config map that gets loaded with `extraArgs`
```
extraArgs: "-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/opt/jboss/import.json -Dkeycloak.migration.strategy=OVERWRITE_EXISTING"

```

**Comment by unguiculus** [comment]
That's pretty much what's suggested in the readme: https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#setting-a-custom-realm

**Comment by unguiculus** [comment]
Closing this as solved.
